change 'elif' to 'case' when it is adequate on major scripts

diff --git a/bridges_activate_old b/bridges_activate_old
--- a/bridges_activate_old
+++ b/bridges_activate_old
@@ -90,126 +90,127 @@ else
   "  3" "Activate only selected OBFS4 bridges"  \
   "  4" "List all "$number_configured_bridges_total" OBFS4 bridges"  \
   "===" "==============================================================" 3>&1 1>&2 2>&3)
-  exitstatus=$?
 
-  if [ $exitstatus = 0 ]; then
-    if [ "$CHOICE" != " " ]; then
+CHOICE=$(echo "$CHOICE" | tr -d ' ')
+case "$CHOICE" in
 
-      # Activate ALL configured bridges
-      if [ $CHOICE = 1 ]; then
-        sudo sed -i "s/^#Bridge obfs4 /Bridge obfs4 /g" ${TORRC}
+  # Activate ALL configured bridges
+  1)
+    sudo sed -i "s/^#Bridge obfs4 /Bridge obfs4 /g" ${TORRC}
+    activate_obfs4_bridges bridges_activate_old
+    exit 0
+  ;;
+
+  # Activate only bridges, which are ONLINE
+  2)
+    clear
+    online_check $BRIDGE_DB_URL 1 1
+    if [ $OCHECK == 1 ]; then
+      echo -e "${WHITE}[+] OK - we are connected with the bridge database${NOCOLOR}"
+      echo " "
+      echo -e "${RED}[+] Checking for bridges to activate - please wait...${NOCOLOR}"
+      trap "bash bridges_activate_old; exit 0" SIGINT
+      i=0
+      while [ $i -lt $number_configured_bridges_deactivated ]
+      do
+        bridge_address=$(cut -d ' ' -f2- <<< ${configured_bridges_deactivated[$i]})
+        bridge_hash=$(cut -d ' ' -f3 <<< $bridge_address)
+        if [ $CLEARNET_DECISSION == 1 ]; then
+          bridge_status=$(./bridges_check.py -f $bridge_hash)
+        else
+          bridge_status=$(./bridges_check.py --network=tor -f $bridge_hash)
+        fi
+        j=0
+        if [ $bridge_status == 1 ]; then
+          j=$(($i + 1))
+          echo -e "${RED}[+] Activating bridge number $j${NOCOLOR}"
+          #This is necessary to work with special characters in sed
+          ORIGINAL_STR="#Bridge $bridge_address"
+          ORIGINAL_STR="$(<<< "$ORIGINAL_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
+          ORIGINAL_STR="^$ORIGINAL_STR"
+          REPLACEMENT_STR="Bridge $bridge_address"
+          REPLACEMENT_STR="$(<<< "$REPLACEMENT_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
+          sudo sed -i "s/${ORIGINAL_STR}/${REPLACEMENT_STR}/g" ${TORRC}
+        fi
+        i=$(( $i + 1 ))
+      done
+      echo " "
+      read -n 1 -s -r -p "Press any key to continue"
+      clear
+      if [ $j -gt 0 ]; then
         activate_obfs4_bridges bridges_activate_old
         exit 0
-
-      # Activate only bridges, which are ONLINE
-      elif [ $CHOICE = 2 ]; then
+      else
+        echo ""
+        echo -e "${WHITE}[!] There are no usable OBFS4 bridges :(  ${NOCOLOR}"
+        echo -e "${RED}[+] Please add some new OBFS4 bridges first! ${NOCOLOR}"
+        echo " "
+        read -n 1 -s -r -p "Press any key to continue"
         clear
-        online_check $BRIDGE_DB_URL 1 1
-        if [ $OCHECK == 1 ]; then
-          echo -e "${WHITE}[+] OK - we are connected with the bridge database${NOCOLOR}"
-          echo " "
-          echo -e "${RED}[+] Checking for bridges to activate - please wait...${NOCOLOR}"
-          trap "bash bridges_activate_old; exit 0" SIGINT
-          i=0
-          while [ $i -lt $number_configured_bridges_deactivated ]
-          do
-            bridge_address=$(cut -d ' ' -f2- <<< ${configured_bridges_deactivated[$i]})
-            bridge_hash=$(cut -d ' ' -f3 <<< $bridge_address)
-            if [ $CLEARNET_DECISSION == 1 ]; then
-              bridge_status=$(./bridges_check.py -f $bridge_hash)
-            else
-              bridge_status=$(./bridges_check.py --network=tor -f $bridge_hash)
-            fi
-            j=0
-            if [ $bridge_status == 1 ]; then
-              j=$(($i + 1))
-              echo -e "${RED}[+] Activating bridge number $j${NOCOLOR}"
-              #This is necessary to work with special characters in sed
-              ORIGINAL_STR="#Bridge $bridge_address"
-              ORIGINAL_STR="$(<<< "$ORIGINAL_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
-              ORIGINAL_STR="^$ORIGINAL_STR"
-              REPLACEMENT_STR="Bridge $bridge_address"
-              REPLACEMENT_STR="$(<<< "$REPLACEMENT_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
-              sudo sed -i "s/${ORIGINAL_STR}/${REPLACEMENT_STR}/g" ${TORRC}
-            fi
-            i=$(( $i + 1 ))
-          done
-          echo " "
-          read -n 1 -s -r -p "Press any key to continue"
-          clear
-          if [ $j -gt 0 ]; then
-            activate_obfs4_bridges bridges_activate_old
-            exit 0
-          else
-            echo ""
-            echo -e "${WHITE}[!] There are no usable OBFS4 bridges :(  ${NOCOLOR}"
-            echo -e "${RED}[+] Please add some new OBFS4 bridges first! ${NOCOLOR}"
-            echo " "
-            read -n 1 -s -r -p "Press any key to continue"
-            clear
-            exit 0
-          fi
-        else
-          echo ""
-          echo -e "${WHITE}[!] OH NO! - no connection to the bridge database :( ${NOCOLOR}"
-          echo -e "${WHITE}[!] Can't fetch the status of the bridges - ABORTING :( ${NOCOLOR}"
-          echo " "
-          read -n 1 -s -r -p "Press any key to continue"
-          clear
-          exit 0
-        fi
         exit 0
+      fi
+    else
+      echo ""
+      echo -e "${WHITE}[!] OH NO! - no connection to the bridge database :( ${NOCOLOR}"
+      echo -e "${WHITE}[!] Can't fetch the status of the bridges - ABORTING :( ${NOCOLOR}"
+      echo " "
+      read -n 1 -s -r -p "Press any key to continue"
+      clear
+      exit 0
+    fi
+    exit 0
+  ;;
 
-      # Activate only selected bridges
-      elif [ $CHOICE = 3 ]; then
-        INPUT=$(cat text/activate-selected-bridges-text)
-        if (whiptail --title "TorBox - INFO" --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
-          number_to_be_activated=$(whiptail --title "TorBox - INFO" --inputbox "\n\nWhich bridge number(s) do you like to activate? Put in all bridge numbers separated by a comma (for example 1,2,3,10)" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3)
-          number_to_be_activated=$(cut -f1- -d ',' --output-delimiter=' ' <<< $number_to_be_activated)
+  # Activate only selected bridges
+  3)
+    INPUT=$(cat text/activate-selected-bridges-text)
+    if (whiptail --title "TorBox - INFO" --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
+      number_to_be_activated=$(whiptail --title "TorBox - INFO" --inputbox "\n\nWhich bridge number(s) do you like to activate? Put in all bridge numbers separated by a comma (for example 1,2,3,10)" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3)
+      number_to_be_activated=$(cut -f1- -d ',' --output-delimiter=' ' <<< $number_to_be_activated)
+      activate_number=$(cut -d ' ' -f1 <<< $number_to_be_activated)
+      clear
+      echo -e "${RED}[+] Checking for bridges to activate - please wait...${NOCOLOR}"
+      j=0
+      while [[ ! -z "$activate_number" && $activate_number -gt 0 && $activate_number -le $number_configured_bridges_deactivated ]]
+      do
+        i=$(( $activate_number - 1 ))
+        bridge_address=$(cut -d ' ' -f2- <<< ${configured_bridges_deactivated[$i]})
+        # Row below is not necessary?
+        # bridge_hash=$(cut -d ' ' -f3 <<< $bridge_address)
+        j=$(($i + 1))
+        echo -e "${RED}[+] Activating bridge number $j${NOCOLOR}"
+        #This is necessary to work with special characters in sed
+        ORIGINAL_STR="#Bridge $bridge_address"
+        ORIGINAL_STR="$(<<< "$ORIGINAL_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
+        ORIGINAL_STR="^$ORIGINAL_STR"
+        REPLACEMENT_STR="Bridge $bridge_address"
+        REPLACEMENT_STR="$(<<< "$REPLACEMENT_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
+        sudo sed -i "s/${ORIGINAL_STR}/${REPLACEMENT_STR}/g" ${TORRC}
+        if [ "$activate_number" = "$number_to_be_activated" ]; then
+          activate_number=0
+        else
+          number_to_be_activated=$(cut -d ' ' -f2- <<< $number_to_be_activated)
           activate_number=$(cut -d ' ' -f1 <<< $number_to_be_activated)
-          clear
-          echo -e "${RED}[+] Checking for bridges to activate - please wait...${NOCOLOR}"
-          j=0
-          while [[ "$activate_number" != " " && $activate_number -gt 0 && $activate_number -le $number_configured_bridges_deactivated ]]
-          do
-            i=$(( $activate_number - 1 ))
-            bridge_address=$(cut -d ' ' -f2- <<< ${configured_bridges_deactivated[$i]})
-            # Row below is not necessary?
-            # bridge_hash=$(cut -d ' ' -f3 <<< $bridge_address)
-            j=$(($i + 1))
-            echo -e "${RED}[+] Activating bridge number $j${NOCOLOR}"
-            #This is necessary to work with special characters in sed
-            ORIGINAL_STR="#Bridge $bridge_address"
-            ORIGINAL_STR="$(<<< "$ORIGINAL_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
-            ORIGINAL_STR="^$ORIGINAL_STR"
-            REPLACEMENT_STR="Bridge $bridge_address"
-            REPLACEMENT_STR="$(<<< "$REPLACEMENT_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
-            sudo sed -i "s/${ORIGINAL_STR}/${REPLACEMENT_STR}/g" ${TORRC}
-            if [ "$activate_number" = "$number_to_be_activated" ]; then
-              activate_number=0
-            else
-              number_to_be_activated=$(cut -d ' ' -f2- <<< $number_to_be_activated)
-              activate_number=$(cut -d ' ' -f1 <<< $number_to_be_activated)
-            fi
-          done
-          echo " "
-          read -n 1 -s -r -p "Press any key to continue"
-          clear
-          if [ $j -gt 0 ]; then
-            activate_obfs4_bridges bridges_activate_old
-            exit 0
-          fi
         fi
-
-      # List all bridges configured in torrc and if online display the status of the bridges
-      elif [ $CHOICE = 4 ]; then
-        list_all_obfs4_bridges
+      done
+      echo " "
+      read -n 1 -s -r -p "Press any key to continue"
+      clear
+      if [ $j -gt 0 ]; then
+        activate_obfs4_bridges bridges_activate_old
+        exit 0
       fi
     fi
-  else
+  ;;
+
+  # List all bridges configured in torrc and if online display the status of the bridges
+  4)
+    list_all_obfs4_bridges
+  ;;
+
+  *)
     clear
     exit 0
-  fi
-fi
+esac
 bash bridges_activate_old
 exit 0
diff --git a/bridges_deactivate_old b/bridges_deactivate_old
--- a/bridges_deactivate_old
+++ b/bridges_deactivate_old
@@ -96,139 +96,140 @@ else
   "  3" "Deactivate only selected OBFS4 bridges"  \
   "  4" "List all "$number_configured_bridges_total" OBFS4 bridges"  \
   "===" "==============================================================" 3>&1 1>&2 2>&3)
-  exitstatus=$?
 
-  if [ $exitstatus = 0 ]; then
-    if [ "$CHOICE" != " " ]; then
+CHOICE=$(echo "$CHOICE" | tr -d ' ')
+case "$CHOICE" in
 
-      # Deactivate ALL configured bridges
-      if [ $CHOICE = 1 ]; then
+  # Deactivate ALL configured bridges
+  1)
+    deactivate_obfs4_bridges
+    clear
+    sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
+    restarting_tor bridges_deactivate_old
+    exit 0
+  ;;
+
+  # Deactivate only bridges, which are OFFLINE or do not exist anymore
+  2)
+    clear
+    online_check $BRIDGE_DB_URL 1 1
+    if [ $OCHECK == 1 ]; then
+      echo -e "${WHITE}[+] OK - we are connected with the bridge database${NOCOLOR}"
+      echo " "
+      echo -e "${RED}[+] Checking for bridges to deactivate - please wait...${NOCOLOR}"
+      trap "bash bridges_deactivate_old; exit 0" SIGINT
+      j=0
+      i=0
+      while [ $i -lt $number_configured_bridges_activated ]
+      do
+        bridge_address=$(cut -d ' ' -f2- <<< ${configured_bridges_activated[$i]})
+        bridge_hash=$(cut -d ' ' -f3 <<< $bridge_address)
+        if [ $CLEARNET_DECISSION == 1 ]; then
+          bridge_status=$(./bridges_check.py -f $bridge_hash)
+        else
+          bridge_status=$(./bridges_check.py --network=tor -f $bridge_hash)
+        fi
+        if [ $bridge_status == 0 ] || [ $bridge_status == 2 ]; then
+          j=$(($j + 1))
+          echo -e "${RED}[+] Deactivating bridge with the hash $bridge_hash${NOCOLOR}"
+          #This is necessary to work with special characters in sed
+          ORIGINAL_STR="Bridge $bridge_address"
+          ORIGINAL_STR="$(<<< "$ORIGINAL_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
+          ORIGINAL_STR="^$ORIGINAL_STR"
+          REPLACEMENT_STR="#Bridge $bridge_address"
+          REPLACEMENT_STR="$(<<< "$REPLACEMENT_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
+          sudo sed -i "s/${ORIGINAL_STR}/${REPLACEMENT_STR}/g" ${TORRC}
+        fi
+        i=$(( $i + 1 ))
+      done
+      if [ $j = 0 ]; then
+        echo " "
+        echo -e "${WHITE}[!] All checked OBFS4 do exist and are online -> nothing to deactivate!${NOCOLOR}"
+        sleep 5
+        clear
+      else
+        echo " "
+        read -n 1 -s -r -p "Press any key to continue"
+        clear
+        number_of_bridges
+        if [ $number_configured_bridges_activated = 0 ]; then
+          deactivate_obfs4_bridges
+          clear
+          sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
+          restarting_tor bridges_deactivate_old
+        else
+          activate_obfs4_bridges bridges_deactivate_old
+          exit 0
+        fi
+      fi
+    else
+      echo -e "${WHITE}[+] OH NO! - no connection to the bridge database :( ${NOCOLOR}"
+      echo -e "${WHITE}[+] Can't fetch the status of the bridges - ABORTING :( ${NOCOLOR}"
+      sleep 5
+      clear
+    fi
+    exit 0
+  ;;
+
+  # Deactivate only selected bridges
+  3)
+    INPUT=$(cat text/deactivate-selected-bridges-text)
+    if (whiptail --title "TorBox - INFO" --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
+      number_to_be_deactivated=$(whiptail --title "TorBox - INFO" --inputbox "\n\nWhich bridge number(s) do you like to deactivate? Put in all bridge numbers separated by a comma (for example 1,2,3,10)" $MENU_HEIGHT_25 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3)
+      number_to_be_deactivated=$(cut -f1- -d ',' --output-delimiter=' ' <<< $number_to_be_deactivated)
+      deactivate_number=$(cut -d ' ' -f1 <<< $number_to_be_deactivated)
+      number_configured_bridges_activated=$(( $number_configured_bridges_deactivated + $number_configured_bridges_activated ))
+      clear
+      echo -e "${RED}[+] Checking for bridges to deactivate - please wait...${NOCOLOR}"
+      j=0
+      while [[ "$deactivate_number" != " " && $deactivate_number -gt 0 && $deactivate_number -gt $number_configured_bridges_deactivated && $deactivate_number -le $number_configured_bridges_activated ]]
+      do
+        i=$(( $deactivate_number - $number_configured_bridges_deactivated - 1 ))
+        bridge_address=$(cut -d ' ' -f2- <<< ${configured_bridges_activated[$i]})
+        # Row below is not necessary?
+        # bridge_hash=$(cut -d ' ' -f3 <<< $bridge_address)
+        j=$(($j + 1))
+        echo -e "${RED}[+] Dectivating bridge number $deactivate_number${NOCOLOR}"
+        #This is necessary to work with special characters in sed
+        ORIGINAL_STR="Bridge $bridge_address"
+        ORIGINAL_STR="$(<<< "$ORIGINAL_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
+        ORIGINAL_STR="^$ORIGINAL_STR"
+        REPLACEMENT_STR="#Bridge $bridge_address"
+        REPLACEMENT_STR="$(<<< "$REPLACEMENT_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
+        sudo sed -i "s/${ORIGINAL_STR}/${REPLACEMENT_STR}/g" ${TORRC}
+        if [ "$deactivate_number" = "$number_to_be_deactivated" ]; then
+          deactivate_number=0
+        else
+          number_to_be_deactivated=$(cut -d ' ' -f2- <<< $number_to_be_deactivated)
+          deactivate_number=$(cut -d ' ' -f1 <<< $number_to_be_deactivated)
+        fi
+      done
+      echo " "
+      read -n 1 -s -r -p "Press any key to continue"
+      clear
+      number_of_bridges
+      if [ $number_configured_bridges_activated = 0 ]; then
         deactivate_obfs4_bridges
         clear
         sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
         restarting_tor bridges_deactivate_old
-        exit 0
-
-      # Deactivate only bridges, which are OFFLINE or do not exist anymore
-      elif [ $CHOICE = 2 ]; then
-        clear
-        online_check $BRIDGE_DB_URL 1 1
-        if [ $OCHECK == 1 ]; then
-          echo -e "${WHITE}[+] OK - we are connected with the bridge database${NOCOLOR}"
-          echo " "
-          echo -e "${RED}[+] Checking for bridges to deactivate - please wait...${NOCOLOR}"
-          trap "bash bridges_deactivate_old; exit 0" SIGINT
-          j=0
-          i=0
-          while [ $i -lt $number_configured_bridges_activated ]
-          do
-            bridge_address=$(cut -d ' ' -f2- <<< ${configured_bridges_activated[$i]})
-            bridge_hash=$(cut -d ' ' -f3 <<< $bridge_address)
-            if [ $CLEARNET_DECISSION == 1 ]; then
-              bridge_status=$(./bridges_check.py -f $bridge_hash)
-            else
-              bridge_status=$(./bridges_check.py --network=tor -f $bridge_hash)
-            fi
-            if [ $bridge_status == 0 ] || [ $bridge_status == 2 ]; then
-              j=$(($j + 1))
-              echo -e "${RED}[+] Deactivating bridge with the hash $bridge_hash${NOCOLOR}"
-              #This is necessary to work with special characters in sed
-              ORIGINAL_STR="Bridge $bridge_address"
-              ORIGINAL_STR="$(<<< "$ORIGINAL_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
-              ORIGINAL_STR="^$ORIGINAL_STR"
-              REPLACEMENT_STR="#Bridge $bridge_address"
-              REPLACEMENT_STR="$(<<< "$REPLACEMENT_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
-              sudo sed -i "s/${ORIGINAL_STR}/${REPLACEMENT_STR}/g" ${TORRC}
-            fi
-            i=$(( $i + 1 ))
-          done
-          if [ $j = 0 ]; then
-            echo " "
-            echo -e "${WHITE}[!] All checked OBFS4 do exist and are online -> nothing to deactivate!${NOCOLOR}"
-            sleep 5
-            clear
-          else
-            echo " "
-            read -n 1 -s -r -p "Press any key to continue"
-            clear
-            number_of_bridges
-            if [ $number_configured_bridges_activated = 0 ]; then
-              deactivate_obfs4_bridges
-              clear
-              sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
-              restarting_tor bridges_deactivate_old
-            else
-              activate_obfs4_bridges bridges_deactivate_old
-              exit 0
-            fi
-          fi
-        else
-          echo -e "${WHITE}[+] OH NO! - no connection to the bridge database :( ${NOCOLOR}"
-          echo -e "${WHITE}[+] Can't fetch the status of the bridges - ABORTING :( ${NOCOLOR}"
-          sleep 5
-          clear
+      else
+        if [ $j -gt 0 ]; then
+          activate_obfs4_bridges bridges_deactivate_old
+          exit 0
         fi
-        exit 0
-
-      # Deactivate only selected bridges
-      elif [ $CHOICE = 3 ]; then
-        INPUT=$(cat text/deactivate-selected-bridges-text)
-        if (whiptail --title "TorBox - INFO" --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
-          number_to_be_deactivated=$(whiptail --title "TorBox - INFO" --inputbox "\n\nWhich bridge number(s) do you like to deactivate? Put in all bridge numbers separated by a comma (for example 1,2,3,10)" $MENU_HEIGHT_25 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3)
-          number_to_be_deactivated=$(cut -f1- -d ',' --output-delimiter=' ' <<< $number_to_be_deactivated)
-          deactivate_number=$(cut -d ' ' -f1 <<< $number_to_be_deactivated)
-          number_configured_bridges_activated=$(( $number_configured_bridges_deactivated + $number_configured_bridges_activated ))
-          clear
-          echo -e "${RED}[+] Checking for bridges to deactivate - please wait...${NOCOLOR}"
-          j=0
-          while [[ "$deactivate_number" != " " && $deactivate_number -gt 0 && $deactivate_number -gt $number_configured_bridges_deactivated && $deactivate_number -le $number_configured_bridges_activated ]]
-          do
-            i=$(( $deactivate_number - $number_configured_bridges_deactivated - 1 ))
-            bridge_address=$(cut -d ' ' -f2- <<< ${configured_bridges_activated[$i]})
-            # Row below is not necessary?
-            # bridge_hash=$(cut -d ' ' -f3 <<< $bridge_address)
-            j=$(($j + 1))
-            echo -e "${RED}[+] Dectivating bridge number $deactivate_number${NOCOLOR}"
-            #This is necessary to work with special characters in sed
-            ORIGINAL_STR="Bridge $bridge_address"
-            ORIGINAL_STR="$(<<< "$ORIGINAL_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
-            ORIGINAL_STR="^$ORIGINAL_STR"
-            REPLACEMENT_STR="#Bridge $bridge_address"
-            REPLACEMENT_STR="$(<<< "$REPLACEMENT_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
-            sudo sed -i "s/${ORIGINAL_STR}/${REPLACEMENT_STR}/g" ${TORRC}
-            if [ "$deactivate_number" = "$number_to_be_deactivated" ]; then
-              deactivate_number=0
-            else
-              number_to_be_deactivated=$(cut -d ' ' -f2- <<< $number_to_be_deactivated)
-              deactivate_number=$(cut -d ' ' -f1 <<< $number_to_be_deactivated)
-            fi
-          done
-          echo " "
-          read -n 1 -s -r -p "Press any key to continue"
-          clear
-          number_of_bridges
-          if [ $number_configured_bridges_activated = 0 ]; then
-            deactivate_obfs4_bridges
-            clear
-            sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
-            restarting_tor bridges_deactivate_old
-          else
-            if [ $j -gt 0 ]; then
-              activate_obfs4_bridges bridges_deactivate_old
-              exit 0
-            fi
-          fi
-        fi
-
-      # List all bridges configured in torrc and if online display the status of the bridges
-      elif [ $CHOICE = 4 ]; then
-        list_all_obfs4_bridges
       fi
     fi
-  else
+  ;;
+
+  # List all bridges configured in torrc and if online display the status of the bridges
+  4)
+    list_all_obfs4_bridges
+  ;;
+
+  *)
     clear
     exit 0
-  fi
-fi
+esac
 bash bridges_deactivate_old
 exit 0
diff --git a/bridges_remove_old b/bridges_remove_old
--- a/bridges_remove_old
+++ b/bridges_remove_old
@@ -97,179 +97,181 @@ CHOICE=$(whiptail --cancel-button "Back" --title "TorBox v.0.4.2 - BRIDGE REMOVA
 "  3" "Remove only selected OBFS4 bridges"  \
 "  4" "List all "$number_configured_bridges_total" OBFS4 bridges"  \
 "===" "==============================================================" 3>&1 1>&2 2>&3)
-exitstatus=$?
 
-if [ $exitstatus = 0 ]; then
-  if [ "$CHOICE" != " " ]; then
+CHOICE=$(echo "$CHOICE" | tr -d ' ')
+case "$CHOICE" in
 
-    # Remove ALL configured bridges
-    if [ $CHOICE = 1 ]; then
-      INPUT=$(cat text/delete-all-bridges-text)
-      if (whiptail --title "TorBox - INFO" --defaultno --no-button "DON'T CHANGE" --yes-button "REMOVE ALL BRIDGES" --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
-          sudo cp ${TORRC} ${BAK}
-          deactivate_obfs4_bridges
-          sudo sed -i "/^#Bridge obfs4 /d" ${TORRC}
-          sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
-          clear
-          restarting_tor bridges_remove_old
-      fi
-      exit 0
-
-    # Remove only bridges, which do not exist anymore
-    elif [ $CHOICE = 2 ]; then
-      clear
-      online_check $BRIDGE_DB_URL 1 1
-      if [ $OCHECK == 1 ]; then
-        echo -e "${WHITE}[+] OK - we are connected with the bridge database${NOCOLOR}"
-        echo " "
-        echo -e "${RED}[+] Checking for bridges to remove - please wait...${NOCOLOR}"
+  # Remove ALL configured bridges
+  1)
+    INPUT=$(cat text/delete-all-bridges-text)
+    if (whiptail --title "TorBox - INFO" --defaultno --no-button "DON'T CHANGE" --yes-button "REMOVE ALL BRIDGES" --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
         sudo cp ${TORRC} ${BAK}
-        trap "bash bridges_remove_old; exit 0" SIGINT
-        j=0
-        i=0
-        while [ $i -lt $number_configured_bridges_deactivated ]
-        do
-          bridge_address=$(cut -d ' ' -f2- <<< ${configured_bridges_deactivated[$i]})
-          bridge_hash=$(cut -d ' ' -f3 <<< $bridge_address)
-          if [ $CLEARNET_DECISSION == 1 ]; then
-            bridge_status=$(./bridges_check.py -f $bridge_hash)
-          else
-            bridge_status=$(./bridges_check.py --network=tor -f $bridge_hash)
-          fi
-          if [ $bridge_status == 2 ]; then
-            j=$(($j + 1))
-            echo -e "${RED}[+] Removing bridge with the hash $bridge_hash${NOCOLOR}"
-            #This is necessary to work with special characters in sed
-            ORIGINAL_STR="${configured_bridges_deactivated[$i]}"
-            ORIGINAL_STR="$(<<< "$ORIGINAL_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
-            ORIGINAL_STR="^$ORIGINAL_STR"
-            sudo grep -v "${ORIGINAL_STR}" ${TORRC} > ${TMP}; sudo mv ${TMP} ${TORRC}
-          fi
-          i=$(( $i + 1 ))
-        done
-        i=0
-        while [ $i -lt $number_configured_bridges_activated ]
-        do
-          bridge_address=$(cut -d ' ' -f2- <<< ${configured_bridges_activated[$i]})
-          bridge_hash=$(cut -d ' ' -f3 <<< $bridge_address)
-          if [ $CLEARNET_DECISSION == 1 ]; then
-            bridge_status=$(./bridges_check.py -f $bridge_hash)
-          else
-            bridge_status=$(./bridges_check.py --network=tor -f $bridge_hash)
-          fi
-          if [ $bridge_status == 2 ]; then
-            j=$(($j + 1))
-            echo -e "${RED}[+] Removing bridge with the hash $bridge_hash${NOCOLOR}"
-            #This is necessary to work with special characters in sed
-            ORIGINAL_STR="${configured_bridges_activated[$i]}"
-            ORIGINAL_STR="$(<<< "$ORIGINAL_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
-            ORIGINAL_STR="^$ORIGINAL_STR"
-            sudo grep -v "${ORIGINAL_STR}" ${TORRC} > ${TMP}; sudo mv ${TMP} ${TORRC}
-          fi
-          i=$(( $i + 1 ))
-        done
-        if [ $j = 0 ]; then
-          echo " "
-          echo -e "${WHITE}[!] All checked OBFS4 do exist -> nothing to remove!${NOCOLOR}"
-          sleep 5
-          clear
+        deactivate_obfs4_bridges
+        sudo sed -i "/^#Bridge obfs4 /d" ${TORRC}
+        sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
+        clear
+        restarting_tor bridges_remove_old
+    fi
+    exit 0
+  ;;
+
+  # Remove only bridges, which do not exist anymore
+  2)
+    clear
+    online_check $BRIDGE_DB_URL 1 1
+    if [ $OCHECK == 1 ]; then
+      echo -e "${WHITE}[+] OK - we are connected with the bridge database${NOCOLOR}"
+      echo " "
+      echo -e "${RED}[+] Checking for bridges to remove - please wait...${NOCOLOR}"
+      sudo cp ${TORRC} ${BAK}
+      trap "bash bridges_remove_old; exit 0" SIGINT
+      j=0
+      i=0
+      while [ $i -lt $number_configured_bridges_deactivated ]
+      do
+        bridge_address=$(cut -d ' ' -f2- <<< ${configured_bridges_deactivated[$i]})
+        bridge_hash=$(cut -d ' ' -f3 <<< $bridge_address)
+        if [ $CLEARNET_DECISSION == 1 ]; then
+          bridge_status=$(./bridges_check.py -f $bridge_hash)
         else
-          echo " "
-          read -n 1 -s -r -p "Press any key to continue"
-          clear
-          number_of_bridges
-          if [ "$MODE_BRIDGES" = "UseBridges 1" ]; then
-            if [ $number_configured_bridges_activated = 0 ]; then
-              deactivate_obfs4_bridges
-              clear
-              sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
-              restarting_tor bridges_remove_old
-            else
-			        sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
-              restarting_tor bridges_remove_old
-            fi
-          fi
+          bridge_status=$(./bridges_check.py --network=tor -f $bridge_hash)
         fi
-      else
-        echo -e "${WHITE}[+] OH NO! - no connection to the bridge database :( ${NOCOLOR}"
-        echo -e "${WHITE}[+] Can't fetch the status of the bridges - ABORTING :( ${NOCOLOR}"
+        if [ $bridge_status == 2 ]; then
+          j=$(($j + 1))
+          echo -e "${RED}[+] Removing bridge with the hash $bridge_hash${NOCOLOR}"
+          #This is necessary to work with special characters in sed
+          ORIGINAL_STR="${configured_bridges_deactivated[$i]}"
+          ORIGINAL_STR="$(<<< "$ORIGINAL_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
+          ORIGINAL_STR="^$ORIGINAL_STR"
+          sudo grep -v "${ORIGINAL_STR}" ${TORRC} > ${TMP}; sudo mv ${TMP} ${TORRC}
+        fi
+        i=$(( $i + 1 ))
+      done
+      i=0
+      while [ $i -lt $number_configured_bridges_activated ]
+      do
+        bridge_address=$(cut -d ' ' -f2- <<< ${configured_bridges_activated[$i]})
+        bridge_hash=$(cut -d ' ' -f3 <<< $bridge_address)
+        if [ $CLEARNET_DECISSION == 1 ]; then
+          bridge_status=$(./bridges_check.py -f $bridge_hash)
+        else
+          bridge_status=$(./bridges_check.py --network=tor -f $bridge_hash)
+        fi
+        if [ $bridge_status == 2 ]; then
+          j=$(($j + 1))
+          echo -e "${RED}[+] Removing bridge with the hash $bridge_hash${NOCOLOR}"
+          #This is necessary to work with special characters in sed
+          ORIGINAL_STR="${configured_bridges_activated[$i]}"
+          ORIGINAL_STR="$(<<< "$ORIGINAL_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
+          ORIGINAL_STR="^$ORIGINAL_STR"
+          sudo grep -v "${ORIGINAL_STR}" ${TORRC} > ${TMP}; sudo mv ${TMP} ${TORRC}
+        fi
+        i=$(( $i + 1 ))
+      done
+      if [ $j = 0 ]; then
+        echo " "
+        echo -e "${WHITE}[!] All checked OBFS4 do exist -> nothing to remove!${NOCOLOR}"
         sleep 5
         clear
-      fi
-      exit 0
-
-    # Remove only selected bridges
-    elif [ $CHOICE = 3 ]; then
-      INPUT=$(cat text/delete-selected-bridges-text)
-      if (whiptail --title "TorBox - INFO" --defaultno --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
-        number_to_be_deleted=$(whiptail --title "TorBox - INFO" --inputbox "\n\nWhich bridge number(s) do you like to remove? Put in all bridge numbers separated by a comma (for example 1,2,3,10)" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3)
-        number_to_be_deleted=$(cut -f1- -d ',' --output-delimiter=' ' <<< $number_to_be_deleted)
-        delete_number=$(cut -d ' ' -f1 <<< $number_to_be_deleted)
+      else
+        echo " "
+        read -n 1 -s -r -p "Press any key to continue"
         clear
-        echo -e "${RED}[+] Checking for bridges to remove - please wait...${NOCOLOR}"
-        sudo cp ${TORRC} ${BAK}
-        j=0
-        while [[ "$delete_number" != " " && $delete_number -gt 0 && $delete_number -le $number_configured_bridges_total ]]
-        do
-          if [ $delete_number -gt $number_configured_bridges_deactivated ]; then
-            echo -e "${RED}[+] Removing bridge number $delete_number${NOCOLOR}"
-            j=$(($j + 1))
-            i=$(( $delete_number - $number_configured_bridges_deactivated - 1 ))
-            #This is necessary to work with special characters
-            ORIGINAL_STR="${configured_bridges_activated[$i]}"
-            ORIGINAL_STR="$(<<< "$ORIGINAL_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
-            ORIGINAL_STR="^$ORIGINAL_STR"
-            sudo grep -v "${ORIGINAL_STR}" ${TORRC} > ${TMP}; sudo mv ${TMP} ${TORRC}
-          else
-            echo -e "${RED}[+] Removing bridge number $delete_number${NOCOLOR}"
-            j=$(($j + 1))
-            i=$(( $delete_number - 1 ))
-            #This is necessary to work with special characters
-            ORIGINAL_STR="${configured_bridges_deactivated[$i]}"
-            ORIGINAL_STR="$(<<< "$ORIGINAL_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
-            ORIGINAL_STR="^$ORIGINAL_STR"
-            sudo grep -v "${ORIGINAL_STR}" ${TORRC} > ${TMP}; sudo mv ${TMP} ${TORRC}
-          fi
-          if [ "$delete_number" = "$number_to_be_deleted" ]; then
-            delete_number=0
-          else
-            number_to_be_deleted=$(cut -d ' ' -f2- <<< $number_to_be_deleted)
-            delete_number=$(cut -d ' ' -f1 <<< $number_to_be_deleted)
-          fi
-        done
         number_of_bridges
-        if [ $j = 0 ]; then
-          echo " "
-          echo -e "${WHITE}[!] We had nothing to remove! Did we?${NOCOLOR}"
-          sleep 5
-          clear
-        else
-          echo " "
-          read -n 1 -s -r -p "Press any key to continue"
-          clear
-          number_of_bridges
-          if [ "$MODE_BRIDGES" = "UseBridges 1" ]; then
-            if [ $number_configured_bridges_activated = 0 ]; then
-              deactivate_obfs4_bridges
-              clear
-              sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
-              restarting_tor bridges_remove_old
-            else
-              sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
-              restarting_tor bridges_remove_old
-            fi
+        if [ "$MODE_BRIDGES" = "UseBridges 1" ]; then
+          if [ $number_configured_bridges_activated = 0 ]; then
+            deactivate_obfs4_bridges
+            clear
+            sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
+            restarting_tor bridges_remove_old
+          else
+            sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
+            restarting_tor bridges_remove_old
           fi
         fi
       fi
-
-    # List all bridges configured in torrc and if online display the status of the bridges
-    elif [ $CHOICE = 4 ]; then
-      list_all_obfs4_bridges
+    else
+      echo -e "${WHITE}[+] OH NO! - no connection to the bridge database :( ${NOCOLOR}"
+      echo -e "${WHITE}[+] Can't fetch the status of the bridges - ABORTING :( ${NOCOLOR}"
+      sleep 5
+      clear
     fi
-  fi
-else
-  clear
-  exit 0
-fi
+    exit 0
+  ;;
+
+  # Remove only selected bridges
+  3)
+    INPUT=$(cat text/delete-selected-bridges-text)
+    if (whiptail --title "TorBox - INFO" --defaultno --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
+      number_to_be_deleted=$(whiptail --title "TorBox - INFO" --inputbox "\n\nWhich bridge number(s) do you like to remove? Put in all bridge numbers separated by a comma (for example 1,2,3,10)" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3)
+      number_to_be_deleted=$(cut -f1- -d ',' --output-delimiter=' ' <<< $number_to_be_deleted)
+      delete_number=$(cut -d ' ' -f1 <<< $number_to_be_deleted)
+      clear
+      echo -e "${RED}[+] Checking for bridges to remove - please wait...${NOCOLOR}"
+      sudo cp ${TORRC} ${BAK}
+      j=0
+      while [[ "$delete_number" != " " && $delete_number -gt 0 && $delete_number -le $number_configured_bridges_total ]]
+      do
+        if [ $delete_number -gt $number_configured_bridges_deactivated ]; then
+          echo -e "${RED}[+] Removing bridge number $delete_number${NOCOLOR}"
+          j=$(($j + 1))
+          i=$(( $delete_number - $number_configured_bridges_deactivated - 1 ))
+          #This is necessary to work with special characters
+          ORIGINAL_STR="${configured_bridges_activated[$i]}"
+          ORIGINAL_STR="$(<<< "$ORIGINAL_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
+          ORIGINAL_STR="^$ORIGINAL_STR"
+          sudo grep -v "${ORIGINAL_STR}" ${TORRC} > ${TMP}; sudo mv ${TMP} ${TORRC}
+        else
+          echo -e "${RED}[+] Removing bridge number $delete_number${NOCOLOR}"
+          j=$(($j + 1))
+          i=$(( $delete_number - 1 ))
+          #This is necessary to work with special characters
+          ORIGINAL_STR="${configured_bridges_deactivated[$i]}"
+          ORIGINAL_STR="$(<<< "$ORIGINAL_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
+          ORIGINAL_STR="^$ORIGINAL_STR"
+          sudo grep -v "${ORIGINAL_STR}" ${TORRC} > ${TMP}; sudo mv ${TMP} ${TORRC}
+        fi
+        if [ "$delete_number" = "$number_to_be_deleted" ]; then
+          delete_number=0
+        else
+          number_to_be_deleted=$(cut -d ' ' -f2- <<< $number_to_be_deleted)
+          delete_number=$(cut -d ' ' -f1 <<< $number_to_be_deleted)
+        fi
+      done
+      number_of_bridges
+      if [ $j = 0 ]; then
+        echo " "
+        echo -e "${WHITE}[!] We had nothing to remove! Did we?${NOCOLOR}"
+        sleep 5
+        clear
+      else
+        echo " "
+        read -n 1 -s -r -p "Press any key to continue"
+        clear
+        number_of_bridges
+        if [ "$MODE_BRIDGES" = "UseBridges 1" ]; then
+          if [ $number_configured_bridges_activated = 0 ]; then
+            deactivate_obfs4_bridges
+            clear
+            sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
+            restarting_tor bridges_remove_old
+          else
+            sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
+            restarting_tor bridges_remove_old
+          fi
+        fi
+      fi
+    fi
+  ;;
+
+  # List all bridges configured in torrc and if online display the status of the bridges
+  4)
+    list_all_obfs4_bridges
+  ;;
+
+  *)
+    clear
+    exit 0
+esac
 bash bridges_remove_old
 exit 0
