Support for multiple Snowflake bridge lines added - still has to be tested in details

diff --git a/bridges_add_obfs4 b/bridges_add_obfs4
--- a/bridges_add_obfs4
+++ b/bridges_add_obfs4
@@ -57,6 +57,7 @@ TOR_GET_BRIDGES_URL="https://bridges.torproject.org"
 TORRC="/etc/tor/torrc"
 MODE_BRIDGES=$1
 STANDALONE=$2
+COUNTRY=00
 number_bridges=0
 i=0
 
@@ -82,79 +83,120 @@ case "$CHOICE" in
   # Add bridges automatically
   1)
     clear
-    INPUT=$(cat text/add-bridges-automatically-text)
-    if (whiptail --title "TorBox - INFO" --yesno "$INPUT" $MENU_HEIGHT_15 $MENU_WIDTH); then
-      online_check $TOR_GET_BRIDGES_URL 1 1
-      if [ $OCHECK == 1 ]; then
-        echo -e "${RED}[+] Trying to fetch a bridge... this may take some time, please wait!${NOCOLOR}"
-        trap "bash bridges_add_obfs4 $MODE_BRIDGES $STANDALONE; exit 0" SIGINT
-        (rm -r /tmp/captcha.*) 2> /dev/null
-        if [ $CLEARNET_DECISSION == 1 ]; then
-          if [ "$TOR_DNS" == "0" ]; then local_clearnet_dns_resolution_on; fi
-          bridge_address=$(python3 bridges_get.py)
-          if [ "$TOR_DNS" == "0" ]; then local_clearnet_dns_resolution_off; fi
-        else
-          bridge_address=$(python3 bridges_get.py --network=tor)
-        fi
-        if [ "$bridge_address" = "-1" ]; then
-          echo " "
-          echo -e "${RED}[+] Sorry, I couldn't fetch a bridge! Please, try again later or add bridges manually!${NOCOLOR}"
-          echo " "
-          read -n 1 -s -r -p "Press any key to continue"
-          clear
-          exit 0
-        else
-					clear
-					# Create an array
-					SAVEIFS=$IFS   # Save current IFS (Internal Field Separator)
-					IFS=$'\n'      # Change IFS to newline char
-					# shellcheck disable=SC2206
-					bridge_address=($bridge_address) # split the `names` string into an array by the same name
-					IFS=$SAVEIFS   # Restore original IFS
-					number_bridges=${#bridge_address[@]}
-					for (( i=0; i<$number_bridges; i++ ))
-					do
-						echo -e "${WHITE}[!] Sucess!. We fetched $number_bridges bridge(s)${NOCOLOR}"
-						if grep -q "${bridge_address[$i]}" $TORRC ; then
-							echo -e "${RED}[+] Sorry, bridge number $i is already added!${NOCOLOR}"
-						else
-							echo -e "${RED}[+] Adding, bridge number $i...${NOCOLOR}"
-            	if [ "$MODE_BRIDGES" = "UseBridges 1" ]; then
-              	bridge_address[$i]="$(<<< "${bridge_address[$i]}" sed -e 's`obfs4`Bridge obfs4`g')"
-              	bridge_address[$i]=$(echo -e "${bridge_address[$i]}\n")
-            	else
-              	bridge_address[$i]="$(<<< "${bridge_address[$i]}" sed -e 's`obfs4`#Bridge obfs4`g')"
-              	bridge_address[$i]=$(echo -e "${bridge_address[$i]}\n")
-            	fi
-							printf %s"${bridge_address[$i]}\n" | sudo tee -a $TORRC
+		if (whiptail --title "TorBox - ADD BRIDGES" --yesno "Do you want to try to fetch country-specific bridges?" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX); then
+			# The list below was created by following command: cat /usr/share/zoneinfo/iso3166.tab | tail -n +26 | tr '\t' '!' | sed 's/!/\" \"/' | sed 's/^/\"/' | sed 's/$/\"/' | tr '\n' ' '
+			COUNTRY=$(whiptail --menu "Please, select the country in which the Pi is to be used" $MENU_HEIGHT_25 $MENU_WIDTH 17 "AD" "Andorra" "AE" "United Arab Emirates" "AF" "Afghanistan" "AG" "Antigua & Barbuda" "AI" "Anguilla" "AL" "Albania" "AM" "Armenia" "AO" "Angola" "AQ" "Antarctica" "AR" "Argentina" "AS" "Samoa (American)" "AT" "Austria" "AU" "Australia" "AW" "Aruba" "AX" "Åland Islands" "AZ" "Azerbaijan" "BA" "Bosnia & Herzegovina" "BB" "Barbados" "BD" "Bangladesh" "BE" "Belgium" "BF" "Burkina Faso" "BG" "Bulgaria" "BH" "Bahrain" "BI" "Burundi" "BJ" "Benin" "BL" "St Barthelemy" "BM" "Bermuda" "BN" "Brunei" "BO" "Bolivia" "BQ" "Caribbean NL" "BR" "Brazil" "BS" "Bahamas" "BT" "Bhutan" "BV" "Bouvet Island" "BW" "Botswana" "BY" "Belarus" "BZ" "Belize" "CA" "Canada" "CC" "Cocos (Keeling) Islands" "CD" "Congo (Dem. Rep.)" "CF" "Central African Rep." "CG" "Congo (Rep.)" "CH" "Switzerland" "CI" "Côte d'Ivoire" "CK" "Cook Islands" "CL" "Chile" "CM" "Cameroon" "CN" "China" "CO" "Colombia" "CR" "Costa Rica" "CU" "Cuba" "CV" "Cape Verde" "CW" "Curaçao" "CX" "Christmas Island" "CY" "Cyprus" "CZ" "Czech Republic" "DE" "Germany" "DJ" "Djibouti" "DK" "Denmark" "DM" "Dominica" "DO" "Dominican Republic" "DZ" "Algeria" "EC" "Ecuador" "EE" "Estonia" "EG" "Egypt" "EH" "Western Sahara" "ER" "Eritrea" "ES" "Spain" "ET" "Ethiopia" "FI" "Finland" "FJ" "Fiji" "FK" "Falkland Islands" "FM" "Micronesia" "FO" "Faroe Islands" "FR" "France" "GA" "Gabon" "GB" "Britain (UK)" "GD" "Grenada" "GE" "Georgia" "GF" "French Guiana" "GG" "Guernsey" "GH" "Ghana" "GI" "Gibraltar" "GL" "Greenland" "GM" "Gambia" "GN" "Guinea" "GP" "Guadeloupe" "GQ" "Equatorial Guinea" "GR" "Greece" "GS" "South Georgia & the South Sandwich Islands" "GT" "Guatemala" "GU" "Guam" "GW" "Guinea-Bissau" "GY" "Guyana" "HK" "Hong Kong" "HM" "Heard Island & McDonald Islands" "HN" "Honduras" "HR" "Croatia" "HT" "Haiti" "HU" "Hungary" "ID" "Indonesia" "IE" "Ireland" "IL" "Israel" "IM" "Isle of Man" "IN" "India" "IO" "British Indian Ocean Territory" "IQ" "Iraq" "IR" "Iran" "IS" "Iceland" "IT" "Italy" "JE" "Jersey" "JM" "Jamaica" "JO" "Jordan" "JP" "Japan" "KE" "Kenya" "KG" "Kyrgyzstan" "KH" "Cambodia" "KI" "Kiribati" "KM" "Comoros" "KN" "St Kitts & Nevis" "KP" "Korea (North)" "KR" "Korea (South)" "KW" "Kuwait" "KY" "Cayman Islands" "KZ" "Kazakhstan" "LA" "Laos" "LB" "Lebanon" "LC" "St Lucia" "LI" "Liechtenstein" "LK" "Sri Lanka" "LR" "Liberia" "LS" "Lesotho" "LT" "Lithuania" "LU" "Luxembourg" "LV" "Latvia" "LY" "Libya" "MA" "Morocco" "MC" "Monaco" "MD" "Moldova" "ME" "Montenegro" "MF" "St Martin (French)" "MG" "Madagascar" "MH" "Marshall Islands" "MK" "North Macedonia" "ML" "Mali" "MM" "Myanmar (Burma)" "MN" "Mongolia" "MO" "Macau" "MP" "Northern Mariana Islands" "MQ" "Martinique" "MR" "Mauritania" "MS" "Montserrat" "MT" "Malta" "MU" "Mauritius" "MV" "Maldives" "MW" "Malawi" "MX" "Mexico" "MY" "Malaysia" "MZ" "Mozambique" "NA" "Namibia" "NC" "New Caledonia" "NE" "Niger" "NF" "Norfolk Island" "NG" "Nigeria" "NI" "Nicaragua" "NL" "Netherlands" "NO" "Norway" "NP" "Nepal" "NR" "Nauru" "NU" "Niue" "NZ" "New Zealand" "OM" "Oman" "PA" "Panama" "PE" "Peru" "PF" "French Polynesia" "PG" "Papua New Guinea" "PH" "Philippines" "PK" "Pakistan" "PL" "Poland" "PM" "St Pierre & Miquelon" "PN" "Pitcairn" "PR" "Puerto Rico" "PS" "Palestine" "PT" "Portugal" "PW" "Palau" "PY" "Paraguay" "QA" "Qatar" "RE" "Réunion" "RO" "Romania" "RS" "Serbia" "RU" "Russia" "RW" "Rwanda" "SA" "Saudi Arabia" "SB" "Solomon Islands" "SC" "Seychelles" "SD" "Sudan" "SE" "Sweden" "SG" "Singapore" "SH" "St Helena" "SI" "Slovenia" "SJ" "Svalbard & Jan Mayen" "SK" "Slovakia" "SL" "Sierra Leone" "SM" "San Marino" "SN" "Senegal" "SO" "Somalia" "SR" "Suriname" "SS" "South Sudan" "ST" "Sao Tome & Principe" "SV" "El Salvador" "SX" "St Maarten (Dutch)" "SY" "Syria" "SZ" "Eswatini (Swaziland)" "TC" "Turks & Caicos Is" "TD" "Chad" "TF" "French Southern & Antarctic Lands" "TG" "Togo" "TH" "Thailand" "TJ" "Tajikistan" "TK" "Tokelau" "TL" "East Timor" "TM" "Turkmenistan" "TN" "Tunisia" "TO" "Tonga" "TR" "Turkey" "TT" "Trinidad & Tobago" "TV" "Tuvalu" "TW" "Taiwan" "TZ" "Tanzania" "UA" "Ukraine" "UG" "Uganda" "UM" "US minor outlying islands" "US" "United States" "UY" "Uruguay" "UZ" "Uzbekistan" "VA" "Vatican City" "VC" "St Vincent" "VE" "Venezuela" "VG" "Virgin Islands (UK)" "VI" "Virgin Islands (US)" "VN" "Vietnam" "VU" "Vanuatu" "WF" "Wallis & Futuna" "WS" "Samoa (western)" "YE" "Yemen" "YT" "Mayotte" "ZA" "South Africa" "ZM" "Zambia" "ZW" "Zimbabwe" 3>&1 1>&2 2>&3)
+			exitstatus=$?
+			# exitstatus == 255 means that the ESC key was pressed
+			[ "$exitstatus" == "255" ] && COUNTRY=00 || COUNTRY=$(echo $COUNTRY | tr '[:upper:]' '[:lower:]')
+		fi
+		clear
+		online_check $TOR_GET_BRIDGES_URL 1 1
+    if [ $OCHECK == 1 ]; then
+    	echo -e "${RED}[+] Trying to fetch a bridge... this may take some time, please wait!${NOCOLOR}"
+    	trap "bash bridges_add_obfs4 $MODE_BRIDGES $STANDALONE; exit 0" SIGINT
+    	(rm -r /tmp/captcha.*) 2> /dev/null
+    	if [ $CLEARNET_DECISSION == 1 ]; then
+				if [ "$TOR_DNS" == "0" ]; then local_clearnet_dns_resolution_on; fi
+				if [ "$COUNTRY" == "00" ]; then
+					bridge_address=$(python3 bridges_get.py)
+				else
+					bridge_address=$(python3 bridges_get.py -c $COUNTRY)
+					if [ "$bridge_address" = "-2" ]; then
+						bridge_address=$(python3 bridges_get.py)
+						if [ "$bridge_address" != "-1" ]; then
+							echo " "
+							echo -e "${RED}[+] Sorry, there is no specific bridge for that country!${NOCOLOR}"
+							echo -e "${RED}[+] We received general valid bridges!${NOCOLOR}"
+							sleep 5
 						fi
-					done
-          echo ""
-          echo -e "${RED}[+] DONE!${NOCOLOR}"
-          sleep 5
-          clear
-          if [ $STANDALONE = 1 ]; then
-            activate_obfs4_bridges bridges_add_obfs4
-            exit 0
-          fi
-        fi
-      else
-        echo ""
-        echo -e "${WHITE}[!] OH NO! - no connection to the bridge database :( ${NOCOLOR}"
-        echo -e "${WHITE}[!] Can't fetch a bridge - ABORTING :( ${NOCOLOR}"
-        echo " "
-        read -n 1 -s -r -p "Press any key to continue"
-        clear
-        exit 0
-      fi
-    fi
+					fi
+				fi
+				if [ "$TOR_DNS" == "0" ]; then local_clearnet_dns_resolution_off; fi
+			else
+				if [ "$COUNTRY" == "00" ]; then
+					bridge_address=$(python3 bridges_get.py --network=tor)
+				else
+					bridge_address=$(python3 bridges_get.py --network=tor -c $COUNTRY)
+					if [ "$bridge_address" = "-2" ]; then
+						bridge_address=$(python3 bridges_get.py --network=tor)
+						if [ "$bridge_address" != "-1" ]; then
+							echo " "
+							echo -e "${RED}[+] Sorry, there is no specific bridge for that country!${NOCOLOR}"
+							echo -e "${RED}[+] We received general valid bridges!${NOCOLOR}"
+							sleep 5
+						fi
+					fi
+				fi
+    	fi
+			if [ "$bridge_address" = "-1" ]; then
+				echo " "
+				echo -e "${WHITE}[!] NETWORK ERROR!${NOCOLOR}"
+				echo -e "${RED}[+] Sorry, I couldn't fetch a bridge! Please, try again later or add bridges manually!${NOCOLOR}"
+				echo " "
+				read -n 1 -s -r -p "Press any key to continue"
+				clear
+				exit 0
+			elif [ "$bridge_address" = "-2" ]; then
+				echo " "
+				echo -e "${RED}[+] Sorry, there is no specific bridge for that country!${NOCOLOR}"
+				echo " "
+				read -n 1 -s -r -p "Press any key to continue"
+				clear
+				exit 0
+			else
+				clear
+				# Create an array
+				SAVEIFS=$IFS   # Save current IFS (Internal Field Separator)
+				IFS=$'\n'      # Change IFS to newline char
+				# shellcheck disable=SC2206
+				bridge_address=($bridge_address) # split the `names` string into an array by the same name
+				IFS=$SAVEIFS   # Restore original IFS
+				number_bridges=${#bridge_address[@]}
+				n=0
+				for (( i=0; i<number_bridges; i++ ))
+				do
+					[ "$i" == "0" ] && echo -e "${WHITE}[!] Sucess!. We fetched $number_bridges bridge(s)${NOCOLOR}"
+					n=$((n+1))
+					if grep -q "${bridge_address[$i]}" $TORRC ; then
+						echo -e "${RED}[+] Sorry, bridge number $n is already added!${NOCOLOR}"
+					else
+						echo -e "${RED}[+] Adding, bridge number $n...${NOCOLOR}"
+        		if [ "$MODE_BRIDGES" = "UseBridges 1" ]; then
+          		bridge_address[$i]="$(<<< "${bridge_address[$i]}" sed -e 's`obfs4 `Bridge obfs4 `g')"
+          		bridge_address[$i]=$(echo -e "${bridge_address[$i]}\n")
+        		else
+          		bridge_address[$i]="$(<<< "${bridge_address[$i]}" sed -e 's`obfs4 `#Bridge obfs4 `g')"
+          		bridge_address[$i]=$(echo -e "${bridge_address[$i]}\n")
+        		fi
+						printf %s"${bridge_address[$i]}\n" | sudo tee -a $TORRC
+					fi
+				done
+      	echo ""
+      	echo -e "${RED}[+] DONE!${NOCOLOR}"
+      	sleep 5
+      	clear
+      	if [ $STANDALONE = 1 ]; then
+        	activate_obfs4_bridges bridges_add_obfs4
+        	exit 0
+      	fi
+    	fi
+  	else
+    	echo ""
+    	echo -e "${WHITE}[!] OH NO! - no connection to the bridge database :( ${NOCOLOR}"
+    	echo -e "${WHITE}[!] Can't fetch a bridge - ABORTING :( ${NOCOLOR}"
+    	echo " "
+    	read -n 1 -s -r -p "Press any key to continue"
+    	clear
+    	exit 0
+  	fi
   ;;
 
   # Add bridges manually
   2)
     clear
-    whiptail --title "TorBox - INFO" --textbox text/add-bridges-manually-text $MENU_HEIGHT_25 $MENU_WIDTH
-    number_bridges=$(whiptail --title "TorBox - INFO" --inputbox "\n\nHow many bridges do you like to add?" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3)
+    whiptail --title "TorBox - ADD BRIDGES" --textbox text/add-bridges-manually-text $MENU_HEIGHT_25 $MENU_WIDTH
+    number_bridges=$(whiptail --title "TorBox - ADD BRIDGES" --inputbox "\n\nHow many bridges do you like to add?" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3)
     if ! [[ "$number_bridges" =~ ^[0-9]+$  ]]; then
       trap "bash bridges_add_obfs4 $MODE_BRIDGES $STANDALONE; exit 0" EXIT
       echo ""
@@ -167,7 +209,7 @@ case "$CHOICE" in
       i=1
       while [ $i -le $number_bridges ]
       do
-        bridge_address=$(whiptail --title "TorBox - INFO" --inputbox "\n\nInsert one bridge (something like:\nobfs4 xxx.xxx.xxx.xxx:xxxx cert=abcd.. iat-mode=0)" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3)
+        bridge_address=$(whiptail --title "TorBox - ADD BRIDGES" --inputbox "\n\nInsert one bridge (something like:\nobfs4 xxx.xxx.xxx.xxx:xxxx <fingerprint> cert=abcd.. iat-mode=0)" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3)
         bridge_address="$(<<< "$bridge_address" sed -e 's/[[:blank:]]*$//')"
         if [ -z "$bridge_address" ]; then
           trap "bash bridges_add_obfs4 $MODE_BRIDGES $STANDALONE; exit 0" EXIT
diff --git a/bridges_deactivate_snowflake b/bridges_deactivate_snowflake
--- a/bridges_deactivate_snowflake
+++ b/bridges_deactivate_snowflake
@@ -19,10 +19,10 @@
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
 #
 # DESCRIPTION
-# This file activates already configured bridges in /etc/tor/torrc.
+# This file deactivates already configured bridges in /etc/tor/torrc.
 #
 # SYNTAX
-# ./bridges_activate_obfs4
+# ./bridges_deactivate_snowflake
 #
 #
 ###### SET VARIABLES ######
@@ -63,15 +63,15 @@ i=0
 
 ######## PREPARATIONS ########
 #
-# number_of_obfs4_bridges()
-# How many OBFS4 bridges do we have? readarray reads into an array beginning with index 0
+# number_of_snowflake_bridges()
+# How many Snowflake bridges do we have? readarray reads into an array beginning with index 0
 # Following variables can be used:
-# $configured_bridges_deactivated -> An array with all deactivated OBFS4 bridges
-# $configured_bridges_activated -> An array with all activated OBFS4 bridges
-# $number_configured_bridges_deactivated -> Number of deactivated bridges
-# $number_configured_bridges_activated -> Number of activated bridges
-# $number_configured_bridges_total -> Total number of bridges
-number_of_obfs4_bridges
+# $configured_snowflake_bridges_deactivated -> An array with all deactivated Snowflake bridges
+# $configured_snowflake_bridges_activated -> An array with all activated Snowflake bridges
+# $number_configured_snowflake_bridges_deactivatedconfigured_bridges_deactivated -> Number of deactivated bridges
+# $number_configured_snowflake_bridges_activated -> Number of activated bridges
+# $number_configured_snowflake_bridges_total -> Total number of bridges
+number_of_snowflake_bridges
 
 ###########################
 
@@ -80,10 +80,10 @@ if [ $EXITID = "EXITID=1" ]; then
   exit 0
 fi
 
-if [ $number_configured_bridges_deactivated = 0 ]; then
+if [ $number_configured_snowflake_bridges_activated = 0 ]; then
   clear
-  echo -e "${WHITE}[!] There are no deactivated OBFS4 bridges. ${NOCOLOR}"
-  echo -e "${RED}[+] You may use the menu entry \"Deactivate OBFS4...\". ${NOCOLOR}"
+  echo -e "${WHITE}[!] There are no activated Snowflake bridges. ${NOCOLOR}"
+  echo -e "${RED}[+] You may use the menu entry \"Activate configured Snowflake bridges...\". ${NOCOLOR}"
   echo " "
   read -n 1 -s -r -p "Press any key to continue"
   clear
@@ -91,82 +91,87 @@ if [ $number_configured_bridges_deactivated = 0 ]; then
 fi
 
 clear
-CHOICE=$(whiptail --cancel-button "Back" --title "TorBox v.0.5.1 - BRIDGE ACTIVATION MENU" --menu "Choose an option (ESC -> go back)" $MENU_HEIGHT $MENU_WIDTH $MENU_LIST_HEIGHT \
+CHOICE=$(whiptail --cancel-button "Back" --title "TorBox v.0.5.1 - BRIDGE DEACTIVATION MENU" --menu "Choose an option (ESC -> go back)" $MENU_HEIGHT $MENU_WIDTH $MENU_LIST_HEIGHT \
 "==" "===============================================================" \
-" 1" "Activate ALL configured OBFS4 bridges"  \
-" 2" "Activate only OBFS4 bridges, which are ONLINE"  \
-" 3" "Activate only selected OBFS4 bridges"  \
-" 4" "List all $number_configured_bridges_total OBFS4 bridges"  \
+" 1" "Deactivate ALL configured Snowflake bridges and directly connect tor"  \
+" 2" "Deactivate only Snowflake bridges, which are not longer ONLINE"  \
+" 3" "Deactivate only selected Snowflake bridges"  \
+" 4" "List all $number_configured_bridges_total Snowflake bridges"  \
 "==" "===============================================================" \
 3>&1 1>&2 2>&3)
 
 CHOICE=$(echo "$CHOICE" | tr -d ' ')
 case "$CHOICE" in
 
-  # Activate ALL configured bridges
+  # Deactivate ALL configured bridges
   1)
-    sudo sed -i "s/^#Bridge obfs4 /Bridge obfs4 /g" ${TORRC}
 		sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
-    activate_obfs4_bridges bridges_activate_obfs4
+    deactivate_snowflake_bridges bridges_deactivate_snowflake
 		exit 0
   ;;
 
-  # Activate only bridges, which are ONLINE
+  # Deactivate only bridges, which are OFFLINE or do not exist anymore
   2)
     clear
     online_check $BRIDGE_DB_URL 1 1
     if [ $OCHECK == 1 ]; then
       echo -e "${WHITE}[+] OK - we are connected with the bridge database${NOCOLOR}"
       echo " "
-      echo -e "${RED}[+] Checking for bridges to activate - please wait...${NOCOLOR}"
-      trap "bash bridges_activate_obfs4; exit 0" SIGINT
+      echo -e "${RED}[+] Checking for bridges to deactivate - please wait...${NOCOLOR}"
+      trap "bash bridges_deactivate_snowflake; exit 0" SIGINT
+      j=0
       i=0
-			j=0
-      while [ $i -lt $number_configured_bridges_deactivated ]
+      while [ $i -lt $number_configured_snowflake_bridges_activated ]
       do
-        bridge_address=$(cut -d ' ' -f2- <<< ${configured_bridges_deactivated[$i]})
+        bridge_address=$(cut -d ' ' -f2- <<< ${configured_snowflake_bridges_activated[$i]})
         bridge_hash=$(cut -d ' ' -f3 <<< $bridge_address)
         if [ $CLEARNET_DECISSION == 1 ]; then
-					if [ "$TOR_DNS" == "0" ]; then local_clearnet_dns_resolution_on; fi
+          if [ "$TOR_DNS" == "0" ]; then local_clearnet_dns_resolution_on; fi
           bridge_status=$(./bridges_check.py -f $bridge_hash)
-					if [ "$TOR_DNS" == "0" ]; then local_clearnet_dns_resolution_off; fi
+          if [ "$TOR_DNS" == "0" ]; then local_clearnet_dns_resolution_off; fi
         else
           bridge_status=$(./bridges_check.py --network=tor -f $bridge_hash)
         fi
-        if [ $bridge_status == 1 ]; then
-          j=$((i+1))
-          echo -e "${RED}[+] Activating bridge number $j${NOCOLOR}"
+        if [ $bridge_status == 0 ] || [ $bridge_status == 2 ]; then
+          j=$((j+1))
+          echo -e "${RED}[+] Deactivating bridge number $j${NOCOLOR}"
           #This is necessary to work with special characters in sed
-          ORIGINAL_STR="#Bridge $bridge_address"
+          ORIGINAL_STR="Bridge $bridge_address"
           ORIGINAL_STR="$(<<< "$ORIGINAL_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
           ORIGINAL_STR="^$ORIGINAL_STR"
-          REPLACEMENT_STR="Bridge $bridge_address"
+          REPLACEMENT_STR="#Bridge $bridge_address"
           REPLACEMENT_STR="$(<<< "$REPLACEMENT_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
           sudo sed -i "s/${ORIGINAL_STR}/${REPLACEMENT_STR}/g" ${TORRC}
         fi
         i=$((i+1))
       done
-      # We will not use "Press any key to continue" because the User shouldn't have the impression he can CTRL-C the process, which will break torrc
-      sleep 5
-      clear
-      if [ $j -gt 0 ]; then
-				sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
-        activate_obfs4_bridges bridges_activate_obfs4
-        clear
-				exit 0
-      else
-        echo ""
-        echo -e "${WHITE}[!] There are no usable OBFS4 bridges :(  ${NOCOLOR}"
-        echo -e "${RED}[+] Please add some new OBFS4 bridges first! ${NOCOLOR}"
+      if [ $j = 0 ]; then
+        echo " "
+        echo -e "${WHITE}[!] All checked Snowflake do exist and are online -> nothing to deactivate!${NOCOLOR}"
         echo " "
         read -n 1 -s -r -p "Press any key to continue"
         clear
         exit 0
+      else
+        # We will not use "Press any key to continue" because the User shouldn't have the impression he can CTRL-C the process, which will break torrc
+        sleep 5
+        clear
+        number_of_snowflake_bridges
+        if [ $number_configured_snowflake_bridges_activated = 0 ]; then
+			    sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
+					deactivate_snowflake_bridges bridges_deactivate_snowflake
+					clear
+					exit 0
+        else
+					sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
+          activate_snowflake_bridges bridges_deactivate_snowflake
+					clear
+          exit 0
+        fi
       fi
     else
-      echo ""
-      echo -e "${WHITE}[!] OH NO! - no connection to the bridge database :( ${NOCOLOR}"
-      echo -e "${WHITE}[!] Can't fetch the status of the bridges - ABORTING :( ${NOCOLOR}"
+      echo -e "${WHITE}[+] OH NO! - no connection to the bridge database :( ${NOCOLOR}"
+      echo -e "${WHITE}[+] Can't fetch the status of the bridges - ABORTING :( ${NOCOLOR}"
       echo " "
       read -n 1 -s -r -p "Press any key to continue"
       clear
@@ -174,7 +179,7 @@ case "$CHOICE" in
     fi
   ;;
 
-  # Activate only selected bridges
+  # Deactivate only selected bridges
   3)
 		online_check $BRIDGE_DB_URL 1 1
 		clear
@@ -185,10 +190,10 @@ case "$CHOICE" in
 			echo -e "${WHITE}[!] SORRY! - no connection with the bridge database${NOCOLOR}"
 			sleep 2
 		fi
-		number_of_obfs4_bridges
-		if [ "$number_configured_bridges_deactivated" == "0" ]; then
+		number_of_snowflake_bridges
+		if [ "$number_configured_snowflake_bridges_activated" == "0" ]; then
 			echo ""
-			echo -e "${WHITE}[!] There is no deactivated bridge, which can be activated!${NOCOLOR}"
+			echo -e "${WHITE}[!] There is no activated bridge, which can be deactivated!${NOCOLOR}"
 			echo " "
 			read -n 1 -s -r -p "Press any key to continue"
 			clear
@@ -197,11 +202,11 @@ case "$CHOICE" in
 		trap "bash menu-bridges; exit 0" SIGINT
 		echo ""
 		i=0
-		while [ $i -lt $number_configured_bridges_deactivated ]
+		while [ $i -lt $number_configured_snowflake_bridges_activated ]
 		do
 			n=$((i+1))
-			echo -e "${RED}[+] Checking bridge $n of $number_configured_bridges_deactivated bridges${NOCOLOR}"
-			bridge_address=$(cut -d ' ' -f3,4 <<< ${configured_bridges_deactivated[$i]})
+			echo -e "${RED}[+] Checking bridge $n of $number_configured_snowflake_bridges_activated bridges${NOCOLOR}"
+			bridge_address=$(cut -d ' ' -f3,4 <<< ${configured_snowflake_bridges_activated[$i]})
 			if [ $OCHECK == 1 ]; then
 				bridge_ip=$(cut -d ' ' -f1 <<< $bridge_address)
 				bridge_hash=$(cut -d ' ' -f2 <<< $bridge_address)
@@ -231,7 +236,7 @@ case "$CHOICE" in
 				bridge_address_display_list="$(printf "%s\n%s\n" "${bridge_address_display_list}" "${bridge_address_display}")"
 			fi
 		done
-		service_menu checklist "${bridge_address_display_list}" "\nThis is the list of bridges which can still get activated.\nImportant: the bridge status is not always accurate!"
+		service_menu checklist "${bridge_address_display_list}" "\nThis is the list of bridges which can still get deactivated.\nImportant: the bridge status is not always accurate!"
 		if [ "$exitstatus" == "0" ]; then
 			clear
 			sudo cp ${TORRC} ${BAK}
@@ -240,16 +245,16 @@ case "$CHOICE" in
 				i=$((i+1))
 				for SERVICE_NUMBER in $ENTRY_NUMBERS; do
 					if [ "$i" == "$SERVICE_NUMBER" ]; then
-						echo -e "${RED}[+] Activate bridge number $i${NOCOLOR}"
+						echo -e "${RED}[+] Deactivate bridge number $i${NOCOLOR}"
 						bridge_address=$(sed "s/-ONLINE//g" <<< "$bridge_address")
 						bridge_address=$(sed "s/-OFFLINE//g" <<< "$bridge_address")
 						bridge_address=$(sed "s/-REMOVED//g" <<< "$bridge_address")
 						bridge_address=$(sed "s/-/ /g" <<< "$bridge_address")
-        		ORIGINAL_STR="#Bridge obfs4 $bridge_address"
+        		ORIGINAL_STR="Bridge snowflake $bridge_address"
 						#This is necessary to work with special characters in sed
         		ORIGINAL_STR="$(<<< "$ORIGINAL_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
         		ORIGINAL_STR="^$ORIGINAL_STR"
-        		REPLACEMENT_STR="Bridge obfs4 $bridge_address"
+        		REPLACEMENT_STR="#Bridge snowflake $bridge_address"
 						#This is necessary to work with special characters in sed
         		REPLACEMENT_STR="$(<<< "$REPLACEMENT_STR" sed -e 's`[][\\/.*^$]`\\&`g')"
         		sudo sed -i "s/${ORIGINAL_STR}/${REPLACEMENT_STR}/g" ${TORRC}
@@ -260,16 +265,16 @@ case "$CHOICE" in
 			echo -e "${RED}[+] DONE!${NOCOLOR}"
 			sleep 5
 			clear
-			number_of_obfs4_bridges
-      if [ $number_configured_bridges_activated = 0 ]; then
+			number_of_snowflake_bridges
+      if [ $number_configured_snowflake_bridges_activated = 0 ]; then
 		    sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
-				deactivate_obfs4_bridges bridges_activate_obfs4
+				deactivate_snowflake_bridges bridges_deactivate_snowflake
 				clear
 				exit 0
       else
-        if [ $i -gt 0 ]; then
+        if [ $j -gt 0 ]; then
 		    	sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
-          activate_obfs4_bridges bridges_activate_obfs4
+          activate_snowflake_bridges bridges_deactivate_snowflake
 					clear
           exit 0
         fi
@@ -279,12 +284,12 @@ case "$CHOICE" in
 
   # List all bridges configured in torrc and if online display the status of the bridges
   4)
-    list_all_obfs4_bridges
+    list_all_snowflake_bridges
   ;;
 
   *)
     clear
     exit 0
 esac
-bash bridges_activate_obfs4
+bash bridges_deactivate_snowflake
 exit 0
