menu-config fix

diff --git a/menu-config b/menu-config
--- a/menu-config
+++ b/menu-config
@@ -374,22 +374,25 @@ case "$CHOICE" in
 				exitstatus=$?
 				# exitstatus = 255 means that the ESC key was pressed / exitstatus = 1 is cancelled
 				if [ "$exitstatus" = "1" ] || [ "$exitstatus" = "255" ] ; then exit 0 ; fi
-				INPUT=$(whiptail --title "Changing the configuration of the WLAN" --inputbox "\n\nEnter the new name for TorBox's WLAN:" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3)
-				if [ ! -z "$INPUT" ]; then
-					clear
-					sudo cp ${HOSTAPD} ${HOSTAPD_SAV}
-					echo -e "${RED}[+] Changing SSID...${NOCOLOR}"
-					SSID="ssid=$INPUT"
-					sudo sed -i "s/^ssid=.*/${SSID}/" ${HOSTAPD}
-					sleep 2
-					if (whiptail --yesno "The name of TorBox's WLAN is now changed to\n\n$INPUT.\n\nWould you like to put the changes immediately into effect (this will disconnect the current connection with the TorBox)?" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX); then
-						clear
-						echo " "
-						echo -e "${RED}[+] Activating the name of TorBox's WLAN, now...${NOCOLOR}"
-						echo -e "${WHITE}[!] You have to reconnect to the new WLAN!${NOCOLOR}"
-						(nohup bin/hostapd_fallback) 2>/dev/null
-					fi
-				fi
+			else
+				trap "bash menu-config; exit 0" EXIT
+				exit 0
+			fi
+		fi
+		INPUT=$(whiptail --title "Changing the configuration of the WLAN" --inputbox "\n\nEnter the new name for TorBox's WLAN:" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3)
+		if [ ! -z "$INPUT" ]; then
+			clear
+			sudo cp ${HOSTAPD} ${HOSTAPD_SAV}
+			echo -e "${RED}[+] Changing SSID...${NOCOLOR}"
+			SSID="ssid=$INPUT"
+			sudo sed -i "s/^ssid=.*/${SSID}/" ${HOSTAPD}
+			sleep 2
+			if (whiptail --yesno "The name of TorBox's WLAN is now changed to\n\n$INPUT.\n\nWould you like to put the changes immediately into effect (this will disconnect the current connection with the TorBox)?" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX); then
+				clear
+				echo " "
+				echo -e "${RED}[+] Activating the name of TorBox's WLAN, now...${NOCOLOR}"
+				echo -e "${WHITE}[!] You have to reconnect to the new WLAN!${NOCOLOR}"
+				(nohup bin/hostapd_fallback) 2>/dev/null
 			fi
 		fi
   ;;
@@ -403,20 +406,23 @@ case "$CHOICE" in
 				exitstatus=$?
 				# exitstatus = 255 means that the ESC key was pressed / exitstatus = 1 is cancelled
 				if [ "$exitstatus" = "1" ] || [ "$exitstatus" = "255" ] ; then exit 0 ; fi
-				REGDOMAIN=$(grep "^REGDOMAIN=" ${CRDAFILE})
-				TLC=$(echo "$REGDOMAIN"|cut -c11-12)
-				if [ "$TLC" != "00" ] && [ ! -z "$TLC" ]; then
-					COUNTRY=$(grep ^$TLC /usr/share/zoneinfo/iso3166.tab | tr '\t' '!' | sed "s/^${TLC}!//")
-					INPUT=$(cat text/wrd-text)
-					if (whiptail --yesno "The WLAN regulatory domain is set to $COUNTRY.\n\n$INPUT" 16 $MENU_WIDTH); then change_crda; fi
-				elif [ -z "$TLC" ]; then
-					INPUT=$(cat text/wrd-text)
-					if (whiptail --yesno "The WLAN regulatory domain is not set yet.\n\n$INPUT" 16 $MENU_WIDTH); then change_crda; fi
-				elif [ "$TLC" != "00" ]; then
-					INPUT=$(cat text/wrd-text)
-					if (whiptail --yesno "The WLAN regulatory domain is set to GLOBAL.\n\n$INPUT" 16 $MENU_WIDTH); then change_crda; fi
-				fi
+			else
+				trap "bash menu-config; exit 0" EXIT
+				exit 0
 			fi
+		fi
+		REGDOMAIN=$(grep "^REGDOMAIN=" ${CRDAFILE})
+		TLC=$(echo "$REGDOMAIN"|cut -c11-12)
+		if [ "$TLC" != "00" ] && [ ! -z "$TLC" ]; then
+			COUNTRY=$(grep ^$TLC /usr/share/zoneinfo/iso3166.tab | tr '\t' '!' | sed "s/^${TLC}!//")
+			INPUT=$(cat text/wrd-text)
+			if (whiptail --yesno "The WLAN regulatory domain is set to $COUNTRY.\n\n$INPUT" 16 $MENU_WIDTH); then change_crda; fi
+		elif [ -z "$TLC" ]; then
+			INPUT=$(cat text/wrd-text)
+			if (whiptail --yesno "The WLAN regulatory domain is not set yet.\n\n$INPUT" 16 $MENU_WIDTH); then change_crda; fi
+		elif [ "$TLC" != "00" ]; then
+			INPUT=$(cat text/wrd-text)
+			if (whiptail --yesno "The WLAN regulatory domain is set to GLOBAL.\n\n$INPUT" 16 $MENU_WIDTH); then change_crda; fi
 		fi
   ;;
 
@@ -429,59 +435,62 @@ case "$CHOICE" in
 				exitstatus=$?
 				# exitstatus = 255 means that the ESC key was pressed / exitstatus = 1 is cancelled
 				if [ "$exitstatus" = "1" ] || [ "$exitstatus" = "255" ] ; then exit 0 ; fi
-				if [ "$TOGGLE05" = "2.5 GHz" ]; then
-					if [ ! -z "$CHECK_HD1" ] || [ ! -z "$CHECK_HD2" ]; then
-						clear
-						echo " "
-						echo -e "${WHITE}[!] ATTENTION! The Raspberry Pi 3 Model B does NOT support the 5 GHz band!${NOCOLOR}"
-						echo -e "${WHITE}[!] We stay on the 2.5 GHz band!${NOCOLOR}"
-						echo " "
-						read -n 1 -s -r -p "Press any key to continue"
-						echo " "
-					else
-						REGDOMAIN=$(grep "^REGDOMAIN=" ${CRDAFILE})
-						TLC=$(echo "$REGDOMAIN"|cut -c11-12)
-						if [ "$TLC" = "00" ]; then
-							clear
-							cho " "
-							echo -e "${WHITE}[!] To enable the 5 GHz band, you have to set the WLAN regulatory domain first (don't choose \"00 Global\"!).${NOCOLOR}"
-							echo " "
-							read -n 1 -s -r -p "Press any key to continue"
-							echo " "
-							change_crda
-						fi
-						INPUT=$(cat text/5ghz-text)
-						if (whiptail --title "TorBox - INFO" --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
-							sudo cp ${HOSTAPD} ${HOSTAPD_SAV}
-							sudo sed -i "s/^hw_mode=g/hw_mode=a/" ${HOSTAPD}
-							sudo sed -i "s/^channel.*/channel=36/" ${HOSTAPD}
-							sudo sed -i "s/^#ht_capab=\[HT40-\]\[HT40+\]\[SHORT-GI-20\]\[SHORT-GI-40\]\[DSSS_CCK-40\]/ht_capab=\[HT40-\]\[HT40+\]\[SHORT-GI-20\]\[SHORT-GI-40\]\[DSSS_CCK-40\]/" ${HOSTAPD}
-							if (whiptail --yesno "The frequency of TorBox's WLAN is now changed to 5 GHz.\n\nWould you like to put the changes immediately into effect (this will disconnect the current connection with the TorBox)?" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX); then
-								clear
-								echo " "
-								echo -e "${RED}[+] Activating the 5 GHz band of TorBox's WLAN, now...${NOCOLOR}"
-								echo -e "${WHITE}[!] Please wait, usually the client reconnects automatically. However, you may have to disconnect and reconnect with TorBox's wireless network.${NOCOLOR}"
-								(nohup bin/hostapd_fallback) 2>/dev/null
-								(sudo rm nohup.out) &>/dev/null
-							fi
-						fi
-					fi
-				else
-					sudo sed -i "s/^hw_mode=a/hw_mode=g/" ${HOSTAPD}
-					sudo sed -i "s/^channel.*/channel=6/" ${HOSTAPD}
-					sudo sed -i "s/^vht_oper_chwidth=1/#vht_oper_chwidth=1/" ${HOSTAPD}
-					sudo sed -i "s/^vht_oper_centr_freq_seg0_idx=42/#vht_oper_centr_freq_seg0_idx=42/" ${HOSTAPD}
-					if (whiptail --yesno "The frequency of TorBox's WLAN is now changed to 2.5 GHz.\n\nWould you like to put the changes immediately into effect (this will disconnect the current connection with the TorBox)?" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX); then
-						clear
-						echo " "
-						echo -e "${RED}[+] Activating the 2.5 GHz band of TorBox's WLAN, now...${NOCOLOR}"
-						echo -e "${WHITE}[!] Please wait, usually the client reconnects automatically. However, you may have to disconnect and reconnect with TorBox's wireless network.${NOCOLOR}"
-						sudo systemctl restart hostapd
-					fi
-				fi
-				read_config
+			else
+				trap "bash menu-config; exit 0" EXIT
+				exit 0
 			fi
 		fi
+		if [ "$TOGGLE05" = "2.5 GHz" ]; then
+			if [ ! -z "$CHECK_HD1" ] || [ ! -z "$CHECK_HD2" ]; then
+				clear
+				echo " "
+				echo -e "${WHITE}[!] ATTENTION! The Raspberry Pi 3 Model B does NOT support the 5 GHz band!${NOCOLOR}"
+				echo -e "${WHITE}[!] We stay on the 2.5 GHz band!${NOCOLOR}"
+				echo " "
+				read -n 1 -s -r -p "Press any key to continue"
+				echo " "
+			else
+				REGDOMAIN=$(grep "^REGDOMAIN=" ${CRDAFILE})
+				TLC=$(echo "$REGDOMAIN"|cut -c11-12)
+				if [ "$TLC" = "00" ]; then
+					clear
+					cho " "
+					echo -e "${WHITE}[!] To enable the 5 GHz band, you have to set the WLAN regulatory domain first (don't choose \"00 Global\"!).${NOCOLOR}"
+					echo " "
+					read -n 1 -s -r -p "Press any key to continue"
+					echo " "
+					change_crda
+				fi
+				INPUT=$(cat text/5ghz-text)
+				if (whiptail --title "TorBox - INFO" --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
+					sudo cp ${HOSTAPD} ${HOSTAPD_SAV}
+					sudo sed -i "s/^hw_mode=g/hw_mode=a/" ${HOSTAPD}
+					sudo sed -i "s/^channel.*/channel=36/" ${HOSTAPD}
+					sudo sed -i "s/^#ht_capab=\[HT40-\]\[HT40+\]\[SHORT-GI-20\]\[SHORT-GI-40\]\[DSSS_CCK-40\]/ht_capab=\[HT40-\]\[HT40+\]\[SHORT-GI-20\]\[SHORT-GI-40\]\[DSSS_CCK-40\]/" ${HOSTAPD}
+					if (whiptail --yesno "The frequency of TorBox's WLAN is now changed to 5 GHz.\n\nWould you like to put the changes immediately into effect (this will disconnect the current connection with the TorBox)?" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX); then
+						clear
+						echo " "
+						echo -e "${RED}[+] Activating the 5 GHz band of TorBox's WLAN, now...${NOCOLOR}"
+						echo -e "${WHITE}[!] Please wait, usually the client reconnects automatically. However, you may have to disconnect and reconnect with TorBox's wireless network.${NOCOLOR}"
+						(nohup bin/hostapd_fallback) 2>/dev/null
+						(sudo rm nohup.out) &>/dev/null
+					fi
+				fi
+			fi
+		else
+			sudo sed -i "s/^hw_mode=a/hw_mode=g/" ${HOSTAPD}
+			sudo sed -i "s/^channel.*/channel=6/" ${HOSTAPD}
+			sudo sed -i "s/^vht_oper_chwidth=1/#vht_oper_chwidth=1/" ${HOSTAPD}
+			sudo sed -i "s/^vht_oper_centr_freq_seg0_idx=42/#vht_oper_centr_freq_seg0_idx=42/" ${HOSTAPD}
+			if (whiptail --yesno "The frequency of TorBox's WLAN is now changed to 2.5 GHz.\n\nWould you like to put the changes immediately into effect (this will disconnect the current connection with the TorBox)?" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX); then
+				clear
+				echo " "
+				echo -e "${RED}[+] Activating the 2.5 GHz band of TorBox's WLAN, now...${NOCOLOR}"
+				echo -e "${WHITE}[!] Please wait, usually the client reconnects automatically. However, you may have to disconnect and reconnect with TorBox's wireless network.${NOCOLOR}"
+				sudo systemctl restart hostapd
+			fi
+		fi
+		read_config
   ;;
 
   #Change the WLAN channel
@@ -1131,24 +1140,27 @@ case "$CHOICE" in
 				exitstatus=$?
 				# exitstatus = 255 means that the ESC key was pressed / exitstatus = 1 is cancelled
 				if [ "$exitstatus" = "1" ] || [ "$exitstatus" = "255" ] ; then exit 0 ; fi
-				INPUT=$(cat text/pitft-text)
-		    if (whiptail --defaultno --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
-		     	clear
-		     	online_check
-		     	if [ $OCHECK == 1 ]; then
-		       	sudo apt-get -y install python3-dev
-		       	wget https://raw.githubusercontent.com/adafruit/Raspberry-Pi-Installer-Scripts/main/adafruit-pitft.py
-		       	chmod +x adafruit-pitft.py
-		      	sudo pip3 install Click adafruit-python-shell
-		       	sudo python3 adafruit-pitft.py -u /home/torbox
-		       	rm adafruit-pitft.py
-	      	else
-		       	echo -e "${WHITE}[!] SORRY! - TorBox is not connected with the Internet!${NOCOLOR}"
-		       	echo -e "${RED}[+] For that reason, we cannot execute this function :(${NOCOLOR}"
-		       	echo " "
-		       	read -n 1 -s -r -p "Press any key to continue"
-		     	fi
-		   	fi
+			else
+				trap "bash menu-config; exit 0" EXIT
+				exit 0
+			fi
+		fi
+		INPUT=$(cat text/pitft-text)
+		if (whiptail --defaultno --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
+			clear
+			online_check
+			if [ $OCHECK == 1 ]; then
+				sudo apt-get -y install python3-dev
+				wget https://raw.githubusercontent.com/adafruit/Raspberry-Pi-Installer-Scripts/main/adafruit-pitft.py
+				chmod +x adafruit-pitft.py
+				sudo pip3 install Click adafruit-python-shell
+				sudo python3 adafruit-pitft.py -u /home/torbox
+				rm adafruit-pitft.py
+			else
+				echo -e "${WHITE}[!] SORRY! - TorBox is not connected with the Internet!${NOCOLOR}"
+				echo -e "${RED}[+] For that reason, we cannot execute this function :(${NOCOLOR}"
+				echo " "
+				read -n 1 -s -r -p "Press any key to continue"
 			fi
 		fi
   ;;
