Test: Improved wlan0/wlan1 switch; wlan1 failsave removed

diff --git a/menu b/menu
--- a/menu
+++ b/menu
@@ -41,8 +41,8 @@ NO_SPACER=3
 #Set the the variables for the menu
 MENU_WIDTH=80
 MENU_WIDTH_REDUX=60
-MENU_HEIGHT_25=25
 MENU_HEIGHT_15=15
+MENU_HEIGHT_25=25
 # MENU_HEIGHT should not exceed 26
 MENU_HEIGHT=$((8+NO_ITEMS+NO_SPACER))
 MENU_LIST_HEIGHT=$((NO_ITEMS+NO_SPACER))
@@ -404,6 +404,7 @@ case "$CHOICE" in
 		stty intr q
     sudo tail -f -n 30 /var/log/tor/notices.log | sed -u 's#.*Bootstrapped 100% (done): Done#\x1b[93m&\x1b[0m#' | sed -u 's#Bootstrapped 100% (done): Done#Bootstrapped 100% (done): Done -- YOU CAN PRESS NOW Q!#' | grep -v -e "Rejecting ill-formed reverse lookup" -e "Missing mapping for virtual address" -e "You configured a non-loopback address" -e "opening log file" -e "Application request when we haven't" -e "Giving up. (waiting for circuit)" -e "New control connection opened from" -e "While fetching directory info, no running dirservers known"
 		stty intr ^c
+		trap
   ;;
 
   # Ethernet cable internet eth0 --> wlan0 / eth1 / tun1
@@ -471,6 +472,7 @@ case "$CHOICE" in
             (sudo sh -c "iptables-save > /etc/iptables.ipv4.nat") 2>/dev/null
             clear
             restarting_tor menu
+						trap
             exit 0
       		else
         		sudo bash bin/set_interfaces_2 eth0 wlan0 eth1 $CLIENT_IFACE_TUN1_IP $CAPTIVE
@@ -549,6 +551,7 @@ case "$CHOICE" in
             (sudo sh -c "iptables-save > /etc/iptables.ipv4.nat") 2>/dev/null
             clear
             restarting_tor menu
+						trap
             exit 0
         	else
           	sudo bash bin/set_interfaces_2 wlan1 wlan0 eth0 $CLIENT_IFACE_TUN1_IP $CAPTIVE
@@ -561,109 +564,169 @@ case "$CHOICE" in
     fi
   ;;
 
-  # Wireless network (through the onboard chip; wlan0 --> wlan1 / eth0 / tun1)
+	# Wireless network (through the onboard chip; wlan0 --> wlan1 / eth0 / tun1 /usb0)
   # This menu entry temporary restores the wlan1 / eth0 configuration, which does not survive a reboot!
   # A failsave routine in rc.local takes care of it!
   7)
-    INPUT=$(cat text/wlan0-text)
-    if (whiptail --title "TorBox - INFO (scroll down!)" --scrolltext --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
-			if ! ip link | grep wlan0; then
-				INPUT=$(cat text/no_interface_try_it_anyway-text)
-				if (whiptail --title "TorBox - INFO" --yesno --defaultno --no-button "BACK!" --yes-button "PUSH IT!" "$INPUT" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX); then
-					exitstatus=$?
-					# exitstatus = 255 means that the ESC key was pressed / exitstatus = 1 is cancelled
-					if [ "$exitstatus" = "1" ] || [ "$exitstatus" = "255" ] ; then exit 0 ; fi
-				else
-					trap "bash menu; exit 0" EXIT
-					exit 0
+		# The first part is for TorBox mini
+		if [ "$TORBOX_MINI" -eq "1" ]; then
+			INPUT=$(cat text/wlan0_on_torbox_mini-text)
+			if (whiptail --title "TorBox - INFO (scroll down!)" --scrolltext --yesno "$INPUT" $MENU_HEIGHT_15 $MENU_WIDTH); then
+				if ! ip link | grep wlan0; then
+					INPUT=$(cat text/no_interface_try_it_anyway-text)
+					if (whiptail --title "TorBox - INFO" --yesno --defaultno --no-button "BACK!" --yes-button "PUSH IT!" "$INPUT" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX); then
+						exitstatus=$?
+						# exitstatus = 255 means that the ESC key was pressed / exitstatus = 1 is cancelled
+						if [ "$exitstatus" = "1" ] || [ "$exitstatus" = "255" ] ; then	exit 0 ; fi
+					else
+						trap "bash menu; exit 0" EXIT
+						exit 0
+					fi
 				fi
-			fi
-			# NEW v.0.5.4-post
-			# This routine should make it possible that someone connected through wlan0 without an additional wifi adapter (wlan1) can switch to wlan0 --> eth0
-			WLAN1_UP=$(ip link | grep wlan1 | grep "state UP")
-			ETH0_UP=$(ip link | grep eth0 | grep "state UP")
-			# To check: can I switch from UNKNOWN
-			# NEW with TorBox-mini: TUN1_IP is used for tun1 (TorBox on a Cloud) and usb0 (TroBox mini)
-			if ip link | grep tun1 | grep "state UNKNOWN" ; then
-				TUN1_IP=$(ip addr show tun1 | grep -w 192.168.44.1)
-				CLIENT_IFACE_TUN1_IP="tun1"
 				clear
-			else
-				TUN1_IP=$(ip addr show usb0 | grep -w 192.168.44.1)
-				CLIENT_IFACE_TUN1_IP="usb0"
-				clear
-			fi
-			# This code is only applied, if the client is solely connected through a ethernet cable and not through wlan1
-			if [ -n "$ETH0_UP" ] && [ -z "$WLAN1_UP" ] && [ -z "$TUN1_IP" ] ; then
-				INPUT=$(cat text/eth0-text)
-				if (whiptail --title "TorBox - INFO)" --yesno --defaultno "$INPUT" 21 $MENU_WIDTH); then
-					sed -i "s/^WLAN_FAILSAFE=.*/WLAN_FAILSAFE=0/" ${RUNFILE}
-					sudo cp etc/network/interface/wlan1eth0 /etc/network/interfaces
-					sudo cp etc/iptables.ipv4-wlan1eth0.nat /etc/iptables.ipv4.nat
-					torrc_reset
-					ETH0_exists
-					sudo sed -i "s/^INTERNET_IFACE=.*/INTERNET_IFACE=wlan0/" ${RUNFILE}
-				fi
-			fi
-			TUN1_IP=""
-			CLIENT_IFACE_TUN1_IP=""
-			#
-      display_net_reconfiguration_info
-			(nohup bin/hostapd_fallback_komplex_part_1 wlan1 eth0) 2>/dev/null
-			echo -e "${YELLOW}[+] Step 1 of 2 done${NOCOLOR}"
-			(nohup bin/hostapd_fallback_komplex_part_2 wlan1 eth0) 2>/dev/null
-			echo -e "${YELLOW}[+] Step 2 of 2 done${NOCOLOR}"
-			sleep 2
-			if ip link | grep wlan0; then
-				ask_captive
-      	if ip link | grep wlan1 | grep "state UP" ; then
-        	WLAN1_IP=$(ip addr show wlan1 | grep -w 192.168.42.1)
-        	clear
-      	fi
-      	if ip link | grep eth0 | grep "state UP" ; then
-        	ETH0_IP=$(ip addr show eth0 | grep -w 192.168.43.1)
-        	clear
-      	fi
-        # To check: can I switch from UNKNOWN
-        # NEW with TorBox-mini: TUN1_IP is used for tun1 (TorBox on a Cloud) and usb0 (TroBox mini)
-				if ip link | grep tun1 | grep "state UNKNOWN" ; then
-					TUN1_IP=$(ip addr show tun1 | grep -w 192.168.44.1)
-          CLIENT_IFACE_TUN1_IP="tun1"
-					clear
-        else
-          TUN1_IP=$(ip addr show usb0 | grep -w 192.168.44.1)
-          CLIENT_IFACE_TUN1_IP="usb0"
-          clear
-				fi
-				# Configure torrc depending on the present interfaces
-				if [ -z "$WLAN1_IP" ] && [ -z "$ETH0_IP" ] && [ -z "$TUN1_IP" ]; then
-					whiptail --title "TorBox - INFO" --textbox text/no_interface-text $MENU_HEIGHT_15 $MENU_WIDTH_REDUX
-				else
-					torrc_reset
-					if [ -n "$WLAN1_IP" ] ; then WLAN1_exists; fi
-					if [ -n "$ETH0_IP" ] ; then ETH0_exists; fi
-					if [ -n "$TUN1_IP" ] ; then TUN1_exists; fi
-					sudo sed -i "s/^INTERNET_IFACE=.*/INTERNET_IFACE=wlan0/" ${RUNFILE}
+				echo -e "${YELLOW}[!] IMPORTANT${NOCOLOR}"
+				echo -e "${RED}[+] We possibly have to reconfigure TorBox's network settings!${NOCOLOR}"
+				echo -e "${RED}[+] Usually, the configuration continuous afterward -- however,${NOCOLOR}"
+				echo -e "${RED}    this can take up to ${YELLOW}two minutes.${NOCOLOR}"
+				echo -e "${RED}[+] Was it not successful? You may have to choose the Internet${NOCOLOR}"
+				echo -e "${RED}    source again.${NOCOLOR}"
+				echo ""
+				(nohup bin/hostapd_fallback_komplex_part_1 wlan0 eth1) 2>/dev/null
+				echo -e "${YELLOW}[+] Step 1 of 2 done${NOCOLOR}"
+				(nohup bin/hostapd_fallback_komplex_part_2 wlan0 eth1) 2>/dev/null
+				echo -e "${YELLOW}[+] Step 2 of 2 done${NOCOLOR}"
+				sleep 2
+				if ip link | grep wlan0; then
+					ask_captive
+					if ip link | grep wlan1 | grep "state UP" ; then
+						WLAN1_IP=$(ip addr show wlan1 | grep -w 192.168.42.1)
+						clear
+					fi
+					if ip link | grep eth0 | grep "state UP" ; then
+						ETH0_IP=$(ip addr show eth0 | grep -w 192.168.43.1)
+						clear
+					fi
+					# To check: can I switch from UNKNOWN
+					# NEW with TorBox-mini: TUN1_IP is used for tun1 (TorBox on a Cloud) and usb0 (TroBox mini)
+					if ip link | grep tun1 | grep "state UNKNOWN" ; then
+						TUN1_IP=$(ip addr show tun1 | grep -w 192.168.44.1)
+						CLIENT_IFACE_TUN1_IP="tun1"
+						clear
+					else
+						TUN1_IP=$(ip addr show usb0 | grep -w 192.168.44.1)
+						CLIENT_IFACE_TUN1_IP="usb0"
+						clear
+					fi
+					# Configure torrc depending on the present interfaces
+					if [ -z "$WLAN1_IP" ] && [ -z "$ETH0_IP" ] && [ -z "$TUN1_IP" ]; then
+						whiptail --title "TorBox - INFO" --textbox text/no_interface-text $MENU_HEIGHT_15 $MENU_WIDTH_REDUX
+					else
+						torrc_reset
+						if [ -n "$WLAN1_IP" ] ; then WLAN1_exists; fi
+						if [ -n "$ETH0_IP" ] ; then ETH0_exists; fi
+						if [ -n "$TUN1_IP" ] ; then TUN1_exists; fi
+						sudo sed -i "s/^INTERNET_IFACE=.*/INTERNET_IFACE=wlan0/" ${RUNFILE}
 
-      		# The following line should minimize those cases where a restart is required.
-      		sudo systemctl restart isc-dhcp-server
-      		if [ -z "$INTERNETSELECTION" ]; then
-        		sudo bash bin/set_interfaces_2 wlan0 wlan1 eth0 $CLIENT_IFACE_TUN1_IP $CAPTIVE
-            sleep 2
-						# iptables can only be safed if WLAN_FAILSAFE=0 in torbox.run
-						if grep -q "WLAN_FAILSAFE=0" ${RUNFILE} ; then (sudo sh -c "iptables-save > /etc/iptables.ipv4.nat") 2>/dev/null ; fi
-            clear
-            restarting_tor menu
-            exit 0
-      		else
-        		sudo bash bin/set_interfaces_2 wlan0 wlan1 eth0 $CLIENT_IFACE_TUN1_IP $CAPTIVE
-            exit 0
-      		fi
+						# The following line should minimize those cases where a restart is required.
+						sudo systemctl restart isc-dhcp-server
+						if [ -z "$INTERNETSELECTION" ]; then
+							sudo bash bin/set_interfaces_2 wlan0 wlan1 eth0 $CLIENT_IFACE_TUN1_IP $CAPTIVE
+							clear
+							restarting_tor menu
+							trap
+							exit 0
+						else
+							sudo bash bin/set_interfaces_2 wlan0 wlan1 eth0 $CLIENT_IFACE_TUN1_IP $CAPTIVE
+							exit 0
+						fi
+					fi
+				else
+					whiptail --title "TorBox - INFO" --textbox text/no_wlan0-text $MENU_HEIGHT_15 $MENU_WIDTH_REDUX
 				fi
 			else
-				whiptail --title "TorBox - INFO" --textbox text/no_wlan0-text $MENU_HEIGHT_15 $MENU_WIDTH_REDUX
+				trap "bash menu; exit 0" EXIT
+				exit 0
 			fi
-    fi
+			# END of the first part
+			# The second part is for a regular TorBox
+		else
+			INPUT=$(cat text/wlan0-text)
+    	if (whiptail --title "TorBox - INFO (scroll down!)" --scrolltext --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
+				if ! ip link | grep wlan0; then
+					INPUT=$(cat text/no_interface_try_it_anyway-text)
+					if (whiptail --title "TorBox - INFO" --yesno --defaultno --no-button "BACK!" --yes-button "PUSH IT!" "$INPUT" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX); then
+						exitstatus=$?
+						# exitstatus = 255 means that the ESC key was pressed / exitstatus = 1 is cancelled
+						if [ "$exitstatus" = "1" ] || [ "$exitstatus" = "255" ] ; then exit 0 ; fi
+					else
+						trap "bash menu; exit 0" EXIT
+						exit 0
+					fi
+				fi
+				# NEW v.0.5.4-post
+				# We will first copy the configuration files and than try to reconfigure the network
+				# In case of a restart, the correct configuration should prevent a lock-out and apply the changed configuration
+				# IMPORTANT: if this works well, we should apply the same method for the other interfaces, too!
+				sudo cp etc/network/interface/wlan1eth0 /etc/network/interfaces
+				sudo cp etc/iptables.ipv4-wlan1eth0.nat /etc/iptables.ipv4.nat
+				sudo sed -i "s/^INTERNET_IFACE=.*/INTERNET_IFACE=wlan0/" ${RUNFILE}
+      	display_net_reconfiguration_info
+				(nohup bin/hostapd_fallback_komplex_part_1 wlan1 eth0) 2>/dev/null
+				echo -e "${YELLOW}[+] Step 1 of 2 done${NOCOLOR}"
+				(nohup bin/hostapd_fallback_komplex_part_2 wlan1 eth0) 2>/dev/null
+				echo -e "${YELLOW}[+] Step 2 of 2 done${NOCOLOR}"
+				sleep 2
+				if ip link | grep wlan0; then
+					ask_captive
+      		if ip link | grep wlan1 | grep "state UP" ; then
+        		WLAN1_IP=$(ip addr show wlan1 | grep -w 192.168.42.1)
+        		clear
+      		fi
+      		if ip link | grep eth0 | grep "state UP" ; then
+        		ETH0_IP=$(ip addr show eth0 | grep -w 192.168.43.1)
+        		clear
+      		fi
+        	# To check: can I switch from UNKNOWN
+        	# NEW with TorBox-mini: TUN1_IP is used for tun1 (TorBox on a Cloud) and usb0 (TroBox mini)
+					if ip link | grep tun1 | grep "state UNKNOWN" ; then
+						TUN1_IP=$(ip addr show tun1 | grep -w 192.168.44.1)
+          	CLIENT_IFACE_TUN1_IP="tun1"
+						clear
+        	else
+          	TUN1_IP=$(ip addr show usb0 | grep -w 192.168.44.1)
+          	CLIENT_IFACE_TUN1_IP="usb0"
+          	clear
+					fi
+					# Configure torrc depending on the present interfaces
+					if [ -z "$WLAN1_IP" ] && [ -z "$ETH0_IP" ] && [ -z "$TUN1_IP" ]; then
+						whiptail --title "TorBox - INFO" --textbox text/no_interface-text $MENU_HEIGHT_15 $MENU_WIDTH_REDUX
+					else
+						torrc_reset
+						if [ -n "$WLAN1_IP" ] ; then WLAN1_exists; fi
+						if [ -n "$ETH0_IP" ] ; then ETH0_exists; fi
+						if [ -n "$TUN1_IP" ] ; then TUN1_exists; fi
+						sudo sed -i "s/^INTERNET_IFACE=.*/INTERNET_IFACE=wlan0/" ${RUNFILE}
+
+      			# The following line should minimize those cases where a restart is required.
+      			sudo systemctl restart isc-dhcp-server
+      			if [ -z "$INTERNETSELECTION" ]; then
+        			sudo bash bin/set_interfaces_2 wlan0 wlan1 eth0 $CLIENT_IFACE_TUN1_IP $CAPTIVE
+            	sleep 2
+							# iptables can only be safed if WLAN_FAILSAFE=0 in torbox.run
+							if grep -q "WLAN_FAILSAFE=0" ${RUNFILE} ; then (sudo sh -c "iptables-save > /etc/iptables.ipv4.nat") 2>/dev/null ; fi
+            	clear
+            	restarting_tor menu
+            	exit 0
+      			else
+        			sudo bash bin/set_interfaces_2 wlan0 wlan1 eth0 $CLIENT_IFACE_TUN1_IP $CAPTIVE
+            	exit 0
+      			fi
+					fi
+				else
+					whiptail --title "TorBox - INFO" --textbox text/no_wlan0-text $MENU_HEIGHT_15 $MENU_WIDTH_REDUX
+				fi
+    	fi
+		fi
   ;;
 
   # Cellular or other connections (ppp0; usb0 --> wlan0 / eth0 / tun1)
