New: Tor network bandwidth limitation

diff --git a/menu-config b/menu-config
--- a/menu-config
+++ b/menu-config
@@ -225,6 +225,16 @@ read_config()
 		TOGGLE18="Stop"
 	fi
 
+	# TOGGLE10 shows if tor bandwidth limit is started or not
+	clear
+	if grep -q "^BandwidthRate" ${TORRC} ; then
+		clear
+		TOGGLE10="Stop"
+	else
+		clear
+		TOGGLE10="Start"
+	fi
+
 	# TOGGLE22 shows if the OpenVPN server is configured
 	clear
 	if [[ -e /etc/openvpn/server.conf ]]; then
@@ -266,16 +276,17 @@ CHOICE=$(whiptail --cancel-button "Back" --title "TorBox v.0.5.4 - CONFIGURATION
 "12" "$TOGGLE12 HTTP plain text traffic block $TOGGLE13" \
 "==" "======================================================[Tor]===" \
 "13" "$TOGGLE18 excluding slow tor relays"  \
-"14" "$TOGGLE14 Tor control port access for clients $TOGGLE15" \
-"15" "Enter the advanced tor configuration editor"  \
+"14" "$TOGGLE10 Tor network bandwidth limitation"
+"15" "$TOGGLE14 Tor control port access for clients $TOGGLE15" \
+"16" "Enter the advanced tor configuration editor"  \
 "==" "=============================================[Logging "$TOGGLE03 \
-"16" "Changing the extent of logging ($TOGGLE03b -> $TOGGLE04b)" \
-"17" "Erase all log files" \
+"17" "Changing the extent of logging ($TOGGLE03b -> $TOGGLE04b)" \
+"18" "Erase all log files" \
 "==" "=============================================[Add Features]===" \
-"18" "$TOGGLE22" \
-"19" "Support for Adafruit's PiTFT displays (reboot required)" \
-"20" "Support for 3.5\" no-name TFT displays (reboot required)" \
-"21" "Support for Sixfab Shields/HATs for cellular connections" \
+"19" "$TOGGLE22" \
+"10" "Support for Adafruit's PiTFT displays (reboot required)" \
+"21" "Support for 3.5\" no-name TFT displays (reboot required)" \
+"22" "Support for Sixfab Shields/HATs for cellular connections" \
 3>&1 1>&2 2>&3)
 exitstatus=$?
 # exitstatus == 255 means that the ESC key was pressed
@@ -1006,11 +1017,14 @@ case "$CHOICE" in
 	13)
 		if [ "$TOGGLE18" = "Start" ]; then
     	INPUT=$(cat text/exclude_slow_tor_relays-text)
-			if (whiptail --title "TorBox - INFO" --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
-				SPEED=$(whiptail --title "Speed threshold" --inputbox "\nEnter the speed threeshold in KB/s. All relays below that threshold will be excluded (default: 4000)" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3)
+			if (whiptail --title "TorBox v.0.5.4 - INFO" --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
+				SPEED=$(whiptail --title "TorBox v.0.5.4 - Speed threshold" --inputbox "\nEnter the speed threeshold in KB/s. All relays below that threshold will be excluded (default: 4000)" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3)
 				exitstatus=$?
-				# exitstatus == 255 means that the ESC key was pressed
-				[ "$exitstatus" == "255" ] && exit 1
+				if [ "$exitstatus" == "1" ] || [ "$exitstatus" == "255" ]; then
+					clear
+					trap "bash menu-config; exit 0" EXIT
+					exit 1
+				fi
 				if [ "$SPEED" != "" ] ; then
 					is_integer "${SPEED}"
 					exitstatus=$?
@@ -1032,7 +1046,6 @@ case "$CHOICE" in
 				sudo bin/exclude-slow-tor-relays-ng -b $SPEED
 				sleep 5
 				clear
-#				sudo mv torrc.exclude-slow /etc/tor
 				sudo sed -i "s/^#$TOR_INCLUDE_EX_SLOW/$TOR_INCLUDE_EX_SLOW/" ${TORRC}
 				sudo sed -i "s/^EX_SLOW=.*/EX_SLOW=$SPEED/" ${RUNFILE}
 				restarting_tor menu-config
@@ -1051,8 +1064,72 @@ case "$CHOICE" in
 		fi
   ;;
 
-	#This disables / enables the access to the Tor control port from clients
+	# Limit Bandwidth for tor network traffic
 	14)
+		if [ "$TOGGLE10" = "Start" ]; then
+			OLD_LIMIT=$(grep "^BandwidthRate .*" "$TORRC" | sed "s/^BandwidthRate *//")
+			if [ -z "$OLD_LIMIT" ] ; then OLD_LIMIT="1 GB"; fi
+			INPUT=$(cat text/limit_tor_bandwidth-text)
+			LIMIT=$(whiptail --title "TorBox v.0.5.4 - Bandwidth limit" --inputbox "$INPUT" $MENU_HEIGHT_20 $MENU_WIDTH $OLD_LIMIT 3>&1 1>&2 2>&3)
+			exitstatus=$?
+			if [ "$exitstatus" == "1" ] || [ "$exitstatus" == "255" ]; then
+				clear
+				trap "bash menu-config; exit 0" EXIT
+				exit 1
+			fi
+			if [ "$LIMIT" != "" ] ; then
+				NUMBER=$(cut -d ' ' -f1 <<< $LIMIT)
+				UNIT=$(cut -d ' ' -f2 <<< $LIMIT)
+				if [ -z "$UNIT" ]; then
+					clear
+					echo -e "${YELLOW}[!] WRONG INPUT - bytes, KB, MB or GB is missing!${NOCOLOR}"
+					sleep 5
+					clear
+					trap "bash menu-config; exit 0" EXIT
+					exit 1
+				else
+					if [[ "$UNIT" != "bytes" && "$UNIT" != "KB" && "$UNIT" != "MB" && "$UNIT" != "GB" ]]; then
+						clear
+						echo -e "${YELLOW}[!] WRONG INPUT - Unit has to be bytes, KB, MB or GB!${NOCOLOR}"
+						sleep 5
+						clear
+						trap "bash menu-config; exit 0" EXIT
+						exit 1
+					fi
+				fi
+				is_integer "${NUMBER}"
+				exitstatus=$?
+				# exitstatus == 1 means that $NUMBER is not an integer
+				if [ "$exitstatus" = "1" ]; then
+					clear
+					echo -e "${YELLOW}[!] WRONG INPUT - THE NUMBER IS NOT AN INTEGER!${NOCOLOR}"
+					sleep 5
+					clear
+					trap "bash menu-config; exit 0" EXIT
+					exit 1
+				fi
+				clear
+				echo -e "${RED}[+] Setting a bandwidth limit for the Tor networ traffic...${NOCOLOR}"
+				if grep "^#BandwidthRate" ${TORRC}; then sed -i "s/#BandwidthRate/BandwidthRate/" ${TORRC}; fi
+				if grep "^BandwidthRate" ${TORRC}; then sudo sed -i "s/^BandwidthRate .*/BandwidthRate $NUMBER $UNIT/" ${TORRC}; fi
+				if grep "^#BandwidthBurst" ${TORRC}; then sed -i "s/#BandwidthBurst/BandwidthBurst/" ${TORRC}; fi
+				if grep "^BandwidthBurst" ${TORRC}; then sudo sed -i "s/^BandwidthBurst .*/BandwidthBurst $NUMBER $UNIT/" ${TORRC}; fi
+				sleep 5
+				restarting_tor menu-config
+			fi
+		fi
+		if [ "$TOGGLE10" = "Stop" ]; then
+			clear
+			echo -e "${RED}[+] Removing the bandwidth limit for the Tor networ traffic...${NOCOLOR}"
+			sudo sed -i "s/^BandwidthRate .*/#BandwidthRate 1 GB/" ${TORRC}
+			sudo sed -i "s/^BandwidthBurst .*/#BandwidthBurst 1 GB/" ${TORRC}
+			sleep 5
+			restarting_tor menu-config
+		fi
+	;;
+
+	#This disables / enables the access to the Tor control port from clients
+	15)
     if [ "$TOGGLE14" = "Enable" ]; then
       INPUT=$(cat text/tor_control_port_enable-text)
       if (whiptail --title "TorBox - INFO" --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
@@ -1078,7 +1155,7 @@ case "$CHOICE" in
   ;;
 
 	# Enter the advanced configuration editor
-	15)
+	16)
     INPUT=$(cat text/advanced-OS-text)
     if (whiptail --title "TorBox - INFO" --defaultno --no-button "DON'T CHANGE" --yes-button "CHANGE NOW" --yesno "$INPUT" $MENU_HEIGHT_20 $MENU_WIDTH); then
       sudo cp ${TORRC} ${BAK}
@@ -1092,7 +1169,7 @@ case "$CHOICE" in
   ;;
 
   #This changes the extent of the logging
-	16)
+	17)
     if (whiptail --title "Changing the extent of logging ($TOGGLE03b -> $TOGGLE04b)" --defaultno --yes-button "High" --no-button "LOW" --yesno "\nWould you like to change the extend of logging?" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3); then
 			LOG_STATUS_001=$(sudo systemctl is-active rsyslog)
 			LOG_STATUS_002=$(sudo systemctl is-active systemd-journald.service)
@@ -1143,14 +1220,14 @@ case "$CHOICE" in
   ;;
 
   #This erases all log files
-	17)
+	18)
     clear
     erase_logs
     sleep 2
   ;;
 
 	#This is for installing, managing or removing the OpenVPN server
-	18)
+	19)
 		clear
 		sudo bash install/openvpn-install.sh
 		read_config
@@ -1158,7 +1235,7 @@ case "$CHOICE" in
 	;;
 
   #This is the support for Adafruit's PiTFT displays
-	19)
+	20)
 		if [ -z "$CHECK_HD3" ]; then
 			whiptail --title "TorBox - INFO" --textbox text/no_raspi-text $MENU_HEIGHT_15 $MENU_WIDTH_REDUX
 			trap "bash menu-config; exit 0" EXIT
@@ -1193,7 +1270,7 @@ case "$CHOICE" in
   ;;
 
   #This is the support for 3.5" no-name TFT displays
-	20)
+	21)
 		if [ -z "$CHECK_HD3" ]; then
 			whiptail --title "TorBox - INFO" --textbox text/no_raspi-text $MENU_HEIGHT_15 $MENU_WIDTH_REDUX
 			trap "bash menu-config; exit 0" EXIT
@@ -1273,7 +1350,7 @@ case "$CHOICE" in
   #This is the support for Sixfab Shields/HATs for cellular connections
   #Remark for TorBox v.0.5.4 - we try to do it without an online connection.
   #Preinstalled packages needed: ppp wiringpi
-	21)
+	22)
 		if [ -z "$CHECK_HD3" ]; then
 			whiptail --title "TorBox - INFO" --textbox text/no_raspi-text $MENU_HEIGHT_15 $MENU_WIDTH_REDUX
 			trap "bash menu-config; exit 0" EXIT
