Enabling the installation / update of tor version 0.4.8.x

diff --git a/menu-update b/menu-update
--- a/menu-update
+++ b/menu-update
@@ -64,16 +64,26 @@ CHECK_OS="$(lsb_release -si)"
 CHECK_OS="$(echo "$CHECK_OS" | tail -n1)"
 if [ "$CHECK_OS" == "Debian" ] && [ -f /etc/rpi-issue ] ; then CHECK_OS="Raspbian" ; fi
 
+# NEW post-v.0.5.3: Added
+# Release Page of the official Tor repositories
+TOR_RELEASE="official"
+TORURL="https://gitlab.torproject.org/tpo/core/tor/-/tags"
+TORPATH_TO_RELEASE_TAGS="/tpo/core/tor/-/tags/tor-"
+TOR_HREF_FOR_SED="<a class=\"item-title ref-name\" href=\"/tpo/core/tor/-/tags/tor-"
+TORURL_DL_PARTIAL="https://dist.torproject.org/tor-"
+
+# NEW post-v.0.5.3: Currently not updated
 # Release Page of the unofficial Tor repositories on GitHub
-TORURL="https://github.com/torproject/tor/tags"
-TORPATH_TO_RELEASE_TAGS="/torproject/tor/releases/tag/"
-#WARNING: Sometimes, GitHub will change this prefix!
-#TOR_HREF_FOR_SED="href=\"/torproject/tor/releases/tag/tor-"
-TOR_HREF_FOR_SED1="<h2 data-view-component=\"true\" class=\"f4 d-inline\"><a href=\"/torproject/tor/releases/tag/tor-"
-TOR_HREF_FOR_SED2="\" data-view-component=.*"
+#TOR_RELEASE="unofficial"
+#TORURL="https://github.com/torproject/tor/tags"
+#TORPATH_TO_RELEASE_TAGS="/torproject/tor/releases/tag/"
+# WARNING: Sometimes, GitHub will change this prefix!
+# TOR_HREF_FOR_SED="href=\"/torproject/tor/releases/tag/tor-"
+#TOR_HREF_FOR_SED1="<h2 data-view-component=\"true\" class=\"f4 d-inline\"><a href=\"/torproject/tor/releases/tag/tor-"
+#TOR_HREF_FOR_SED2="\" data-view-component=.*"
 # TORURL_DL_PARTIAL is the the partial download path of the tor release packages
 # (highlighted with "-><-": ->https://github.com/torproject/tor/releases/tag/tor<- -0.4.6.6.tar.gz)
-TORURL_DL_PARTIAL="https://github.com/torproject/tor/archive/refs/tags/tor"
+#TORURL_DL_PARTIAL="https://github.com/torproject/tor/archive/refs/tags/tor-"
 
 # The minimum bandwidth a relay should have, in kilobytes. Relays with less
 # than this amount of bandwidth will be added to the ExcludeNodes line and
@@ -171,11 +181,20 @@ update_tor_preparations()
 	check_install_packages "build-essential automake libevent-dev libssl-dev asciidoc bc devscripts dh-apparmor libcap-dev liblzma-dev libsystemd-dev libzstd-dev quilt zlib1g-dev"
   clear
   echo -e "${RED}[+] Fetching possible tor versions... ${NOCOLOR}"
-  if [ $TORCONNECT -eq 0 ]; then
-    readarray -t torversion_versionsorted < <(curl --silent $TORURL | grep $TORPATH_TO_RELEASE_TAGS | sed -e "s|$TOR_HREF_FOR_SED1||g" | sed -e "s|$TOR_HREF_FOR_SED2||g" | sed -e "s/<a//g" | sed -e "s/\">//g" | sed -e "s/ //g" | sort -r)
-  else
-    readarray -t torversion_versionsorted < <(curl -x socks5h://127.0.0.1:9050 --silent $TORURL | grep $TORPATH_TO_RELEASE_TAGS | sed -e "s|$TOR_HREF_FOR_SED1||g" | sed -e "s|$TOR_HREF_FOR_SED2||g" | sed -e "s/<a//g" | sed -e "s/\">//g" | sed -e "s/ //g" | sort -r)
-  fi
+	# NEW post-v.0.5.3: Added
+	if [ "$TOR_RELEASE" == "official" ]; then
+  	if [ $TORCONNECT -eq 0 ]; then
+			readarray -t torversion_versionsorted < <(curl --silent $TORURL | grep $TORPATH_TO_RELEASE_TAGS | sed -e "s|$TOR_HREF_FOR_SED||g" | sed -e "s/\">.*//g" | sed -e "s/ //g" | sort -r)
+		else
+			readarray -t torversion_versionsorted < <(curl -x socks5h://127.0.0.1:9050 --silent $TORURL | grep $TORPATH_TO_RELEASE_TAGS | sed -e "s|$TOR_HREF_FOR_SED||g" | sed -e "s/\">.*//g" | sed -e "s/ //g" | sort -r)
+		fi
+	elif [ "$TOR_RELEASE" == "unofficial" ]; then
+  	if [ $TORCONNECT -eq 0 ]; then
+    	readarray -t torversion_versionsorted < <(curl --silent $TORURL | grep $TORPATH_TO_RELEASE_TAGS | sed -e "s|$TOR_HREF_FOR_SED1||g" | sed -e "s|$TOR_HREF_FOR_SED2||g" | sed -e "s/<a//g" | sed -e "s/\">//g" | sed -e "s/ //g" | sort -r)
+  	else
+    	readarray -t torversion_versionsorted < <(curl -x socks5h://127.0.0.1:9050 --silent $TORURL | grep $TORPATH_TO_RELEASE_TAGS | sed -e "s|$TOR_HREF_FOR_SED1||g" | sed -e "s|$TOR_HREF_FOR_SED2||g" | sed -e "s/<a//g" | sed -e "s/\">//g" | sed -e "s/ //g" | sort -r)
+  	fi
+	fi
 
   #How many tor version did we fetch?
 	number_torversion=${#torversion_versionsorted[*]}
@@ -230,6 +249,54 @@ update_tor_preparations()
   fi
 }
 
+# This function downloads and updates tor
+# Syntax download_and_compile_tor
+# Used predefined variables: $download_tor_url $filename RED NOCOLOR TORCONNECT
+download_and_compile_tor()
+{
+	if [ $TORCONNECT -eq 0 ]; then
+		wget $download_tor_url
+		DLCHECK=$?
+	else
+		# IMPORTANT: THIS WILL NOT WORK WITH A CAPTCHA!
+		torsocks wget $download_tor_url
+		DLCHECK=$?
+	fi
+	clear
+	if [ $DLCHECK -eq 0 ] ; then
+		echo -e "${RED}[+] Sucessfully downloaded the selected tor version... ${NOCOLOR}"
+		tar xzf $filename
+		echo ""
+		cd "$(ls -d -- tor-*/)"
+		echo -e "${RED}[+] Starting configuring, compiling and installing... ${NOCOLOR}"
+		# Give it a touch of git (without these lines the compilation will break with a git error)
+		git init
+		git add -- *
+		git config --global user.name "torbox"
+		git config --global user.email "torbox@localhost"
+		git commit -m "Initial commit"
+		# Don't use ./autogen.sh
+		sh autogen.sh
+		./configure
+		make
+		sudo make install
+		cd
+		sudo rm -r tor-*
+		cd torbox
+		#Return code for FINISHING / 1=finishing / 0=no finishing needed
+		return 1
+	else
+		echo -e ""
+		echo -e "${WHITE}[!] COULDN'T DOWNLOAD TOR!${NOCOLOR}"
+		echo -e "${RED}[+] The (unofficial) Tor repositories may be blocked or offline!${NOCOLOR}"
+		echo -e "${RED}[+] Please try again later and if the problem persists, please report it${NOCOLOR}"
+		echo -e "${RED}[+] to ${WHITE}anonym@torbox.ch${RED}. ${NOCOLOR}"
+		echo ""
+		read -n 1 -s -r -p $'\e[1;31mPlease press any key to continue... \e[0m'
+		return 0
+	fi
+}
+
 # This function updates TOR to the latest stable version
 # Syntax update_tor
 # Used predefined variables: $torversion_versionsorted_new, RED, WHITE, NOCOLOR, TORURL, TORURL_DL_PARTIAL, TORCONNECT
@@ -243,7 +310,7 @@ update_tor()
   do
     if grep -v "-" <<< "${torversion_versionsorted_new[$i]}"; then
       version_string="$(<<< ${torversion_versionsorted_new[$i]} sed -e 's/ //g')"
-      download_tor_url="$TORURL_DL_PARTIAL-$version_string.tar.gz"
+      download_tor_url="$TORURL_DL_PARTIAL$version_string.tar.gz"
       filename="tor-$version_string.tar.gz"
       i=$number_torversion
     fi
@@ -277,47 +344,9 @@ update_tor()
     echo ""
 		cd
     echo -e "${RED}[+] Download the selected tor version...... ${NOCOLOR}"
-    if [ $TORCONNECT -eq 0 ]; then
-      wget $download_tor_url
-      DLCHECK=$?
-    else
-      # IMPORTANT: THIS WILL NOT WORK WITH A CAPTCHA!
-      torsocks wget $download_tor_url
-      DLCHECK=$?
-    fi
-    if [ $DLCHECK -eq 0 ]; then
-      echo -e "${RED}[+] Sucessfully downloaded the selected tor version... ${NOCOLOR}"
-      tar xzf $filename
-		  echo ""
-			cd "$(ls -d -- tor-*/)"
-      echo -e "${RED}[+] Starting configuring, compiling and installing... ${NOCOLOR}"
-			# Give it a touch of git (without these lines the compilation will break with a git error)
-			git init
-			git add -- *
-			git config --global user.name "torbox"
-			git config --global user.email "torbox@localhost"
-			git commit -m "Initial commit"
-			# Don't use ./autogen.sh
-			sh autogen.sh
-      ./configure
-      make
-      sudo make install
-      cd
-      sudo rm -r tor-*
-			cd torbox
-      #Return code for FINISHING / 1=finishing / 0=no finishing needed
-      return 1
-    else
-      echo -e ""
-      echo -e "${WHITE}[!] COULDN'T DOWNLOAD TOR!${NOCOLOR}"
-      echo -e "${RED}[+] The unofficial Tor repositories may be blocked or offline!${NOCOLOR}"
-      echo -e "${RED}[+] Please try again later and if the problem persists, please report it${NOCOLOR}"
-      echo -e "${RED}[+] to ${WHITE}anonym@torbox.ch${RED}. ${NOCOLOR}"
-      echo ""
-      read -n 1 -s -r -p $'\e[1;31mPlease press any key to continue... \e[0m'
-      clear
-      return 0
-    fi
+		download_and_compile_tor
+		FINISHING=$?
+		return $FINISHING
   else
     return 0
   fi
@@ -349,49 +378,11 @@ select_and_install_tor()
 			cd
       echo -e "${RED}[+] Download the selected tor version...... ${NOCOLOR}"
       version_string="$(<<< ${torversion_versionsorted_new[$CHOICE_TOR]} sed -e 's/ //g')"
-      download_tor_url="$TORURL_DL_PARTIAL-$version_string.tar.gz"
+      download_tor_url="$TORURL_DL_PARTIAL$version_string.tar.gz"
       filename="tor-$version_string.tar.gz"
-      if [ $TORCONNECT -eq 0 ]; then
-        wget $download_tor_url
-        DLCHECK=$?
-      else
-        # IMPORTANT: THIS WILL NOT WORK WITH A CAPTCHA!
-        torsocks wget $download_tor_url
-        DLCHECK=$?
-      fi
-      clear
-      if [ $DLCHECK -eq 0 ] ; then
-        echo -e "${RED}[+] Sucessfully downloaded the selected tor version... ${NOCOLOR}"
-        tar xzf $filename
-        echo ""
-        cd "$(ls -d -- tor-*/)"
-        echo -e "${RED}[+] Starting configuring, compiling and installing... ${NOCOLOR}"
-				# Give it a touch of git (without these lines the compilation will break with a git error)
-				git init
-				git add -- *
-				git config --global user.name "torbox"
-				git config --global user.email "torbox@localhost"
-				git commit -m "Initial commit"
-				# Don't use ./autogen.sh
-        sh autogen.sh
-        ./configure
-        make
-        sudo make install
-        cd
-        sudo rm -r tor-*
-				cd torbox
-        #Return code for FINISHING / 1=finishing / 0=no finishing needed
-        return 1
-      else
-        echo -e ""
-        echo -e "${WHITE}[!] COULDN'T DOWNLOAD TOR!${NOCOLOR}"
-        echo -e "${RED}[+] The unofficial Tor repositories may be blocked or offline!${NOCOLOR}"
-        echo -e "${RED}[+] Please try again later and if the problem persists, please report it${NOCOLOR}"
-        echo -e "${RED}[+] to ${WHITE}anonym@torbox.ch${RED}. ${NOCOLOR}"
-        echo ""
-        read -n 1 -s -r -p $'\e[1;31mPlease press any key to continue... \e[0m'
-        return 0
-      fi
+			download_and_compile_tor
+			FINISHING=$?
+			return $FINISHING
     else
       clear
       echo -e "${WHITE}[!] ABORTED OR WRONG SELECTION!${NOCOLOR}"
@@ -978,6 +969,7 @@ case "$CHOICE" in
         echo ""
         echo -e "${WHITE}[+] FINISHED! Installed Tor version: $TOR_VERS${NOCOLOR}"
         read -n 1 -s -r -p $'\e[1;31mPlease press any key to continue... \e[0m'
+				cd ~/torbox
       fi
     fi
 	;;
