New: hostapd_fallback_komplex_new The AP on wlan1 failsafe is back

diff --git a/menu-danger b/menu-danger
--- a/menu-danger
+++ b/menu-danger
@@ -84,6 +84,13 @@ read_config()
 		TOGGLE19="Stop"
 	fi
 
+	# TOGGLE20 shows if the wlan1 failsafe is enabled or disabled
+	if grep -q "WLAN_FAILSAFE=1" ${RUNFILE} ; then
+		TOGGLE20="Disable"
+	else
+		TOGGLE20="Enable"
+	fi
+
 	# TOGGLE21 shows if SSH pasword login is enabled or disable
 	if sudo grep -q "^PasswordAuthentication no" ${SSHD_CONFIG} ; then
 		TOGGLE21="Enable"
@@ -111,9 +118,10 @@ CHOICE=$(whiptail --cancel-button "Back" --title "TorBox v.0.5.4 - DANGER ZONE" 
 " 2" "Add, change or remove a domain/IP entry in the exclusion lists"  \
 " 3" "List the exclusion lists" \
 "==" "=============================================[Lock-out risk]===" \
-" 4" "$TOGGLE21 SSH password login" \
+" 4" "$TOGGLE20 the AP on wlan1 failsafe" \
+" 5" "$TOGGLE21 SSH password login" \
 "==" "==========================================[Developer Tools]===" \
-" 5" "Forwarding only - tor protection disabled" \
+" 6" "Forwarding only - tor protection disabled" \
 3>&1 1>&2 2>&3)
 exitstatus=$?
 # exitstatus == 255 means that the ESC key was pressed
@@ -438,8 +446,23 @@ case "$CHOICE" in
 		read -n 1 -s -r -p "Press any key to continue"
 	;;
 
-	# Enable/disable SSH password login
+	# Enable/Disable the AP on wlan1 failsafe
 	4)
+		clear
+		INPUT=$(cat text/disable_wlan1_failsafe-text)
+		if (whiptail --title "TorBox - INFO" --defaultno --yesno --no-button "ENABLE" --yes-button "Disable" "$INPUT" $MENU_HEIGHT_20 $MENU_WIDTH); then
+			sed -i "s/^WLAN_FAILSAFE=.*/WLAN_FAILSAFE=0/" ${RUNFILE}
+			(sudo sh -c "iptables-save > /etc/iptables.ipv4.nat") 2>/dev/null
+		else
+			exitstatus=$?
+			# exitstatus == 255 means that the ESC key was pressed
+			[ "$exitstatus" == "255" ] && exit 0
+			sed -i "s/^WLAN_FAILSAFE=.*/WLAN_FAILSAFE=1/" ${RUNFILE}
+		fi
+	;;
+
+	# Enable/disable SSH password login
+	5)
 		clear
 		if [ "$TOGGLE21" == "Disable" ]; then
 			cd
